import { workflowNodeTypes, type Workflow, type WorkflowState } from "./types";
export const WORKFLOW_STORAGE_KEY = "shabis-ai-academy:workflows:v1"; const MAX_WORKFLOWS = 100; const MAX_HISTORY = 100;
const empty = (): WorkflowState => ({ schemaVersion: 2, appVersion: "2.0.0", workflows: [], history: [] });
function validWorkflow(value: unknown): value is Workflow { if (!value || typeof value !== "object") return false; const record = value as Workflow; return typeof record.id === "string" && record.name && typeof record.name.he === "string" && Array.isArray(record.nodes) && record.nodes.length <= 50 && record.nodes.every((node) => typeof node.id === "string" && workflowNodeTypes.includes(node.type) && Array.isArray(node.nextNodeIds)); }
function migrateRun(value: unknown): WorkflowState["history"][number] | undefined { if (!value || typeof value !== "object") return; const run=value as Partial<WorkflowState["history"][number]>; if(typeof run.id!=="string"||typeof run.workflowId!=="string"||!Array.isArray(run.events))return; const completedAt=run.completedAt??run.createdAt; return { ...run, id:run.id, workflowId:run.workflowId, mode:run.mode==="dryRun"?"dryRun":"mock", status:run.status==="failed"||run.status==="waitingForApproval"?run.status:"completed", realityMode:run.status==="waitingForApproval"?"Manual action required":"Simulated", createdAt:run.createdAt??new Date(0).toISOString(), completedAt, durationMs:Math.max(0,run.durationMs??0), input:run.input??{}, output:run.output??"", errors:Array.isArray(run.errors)?run.errors:[], deliverableIds:Array.isArray(run.deliverableIds)?run.deliverableIds:[], evidenceIds:Array.isArray(run.evidenceIds)?run.evidenceIds:[], limitations:Array.isArray(run.limitations)?run.limitations:["Local simulation; no connected provider action was executed."], nextAction:run.nextAction??"Review the report and perform any required real-world action manually.", events:run.events.map((event)=>({...event,result:event.result??(event.status==="completed"?"simulated":event.status)})), validationCodes:Array.isArray(run.validationCodes)?run.validationCodes:[] }; }
export function parseWorkflowState(value: unknown): WorkflowState { if (!value || typeof value !== "object") return empty(); const record = value as Partial<WorkflowState>; const seen = new Set<string>(); return { schemaVersion: 2, appVersion: "2.0.0", workflows: Array.isArray(record.workflows) ? record.workflows.filter(validWorkflow).filter((workflow) => !seen.has(workflow.id) && Boolean(seen.add(workflow.id))).slice(0, MAX_WORKFLOWS) : [], history: Array.isArray(record.history) ? record.history.map(migrateRun).filter((run):run is WorkflowState["history"][number]=>Boolean(run)).slice(-MAX_HISTORY) : [] }; }
export function loadWorkflowState(storage: Pick<Storage,"getItem"> = localStorage) { try { return parseWorkflowState(JSON.parse(storage.getItem(WORKFLOW_STORAGE_KEY) ?? "null")); } catch { return empty(); } }
export function saveWorkflowState(value: WorkflowState, storage: Pick<Storage,"setItem"> = localStorage) { try { storage.setItem(WORKFLOW_STORAGE_KEY, JSON.stringify(parseWorkflowState(value))); } catch { /* optional */ } }

