import type { Workflow, WorkflowNode, WorkflowNodeType } from "./types";
const title = (type: WorkflowNodeType) => ({ he: ({ start: "התחלה", prompt: "פרומפט", agent: "סוכן", knowledgeDocument: "מסמך ידע", validation: "אימות", approval: "אישור", mockRun: "הרצת Mock", dryRun: "הרצת Dry Run", transform: "טרנספורמציה", projectOutput: "פלט לפרויקט", end: "סיום" })[type], en: ({ start: "Start", prompt: "Prompt", agent: "Agent", knowledgeDocument: "Knowledge Document", validation: "Validation", approval: "Approval", mockRun: "Mock Run", dryRun: "Dry Run", transform: "Transform", projectOutput: "Project Output", end: "End" })[type] });
export function createWorkflowNode(type: WorkflowNodeType): WorkflowNode { return { id: crypto.randomUUID(), type, title: title(type), config: {}, nextNodeIds: [] }; }
export function createWorkflow(name: Record<"he" | "en", string>, nodes: WorkflowNode[] = [createWorkflowNode("start"), createWorkflowNode("end")]): Workflow { const now = new Date().toISOString(); return connectSequentially({ id: crypto.randomUUID(), name, description: { he: "", en: "" }, nodes, createdAt: now, updatedAt: now, version: 1, favorite: false }); }
export function connectSequentially(workflow: Workflow): Workflow { return { ...workflow, nodes: workflow.nodes.map((node, index) => ({ ...node, nextNodeIds: workflow.nodes[index + 1] ? [workflow.nodes[index + 1].id] : [] })) }; }
export function addWorkflowNode(workflow: Workflow, type: WorkflowNodeType, index = workflow.nodes.length - 1): Workflow { const nodes = [...workflow.nodes]; nodes.splice(Math.max(0, Math.min(index, nodes.length)), 0, createWorkflowNode(type)); return bump(connectSequentially({ ...workflow, nodes })); }
export function removeWorkflowNode(workflow: Workflow, nodeId: string): Workflow { const node = workflow.nodes.find((item) => item.id === nodeId); if (!node || node.type === "start" || node.type === "end") return workflow; return bump(connectSequentially({ ...workflow, nodes: workflow.nodes.filter((item) => item.id !== nodeId) })); }
export function moveWorkflowNode(workflow: Workflow, nodeId: string, direction: -1 | 1): Workflow { const index = workflow.nodes.findIndex((item) => item.id === nodeId); const target = index + direction; if (index <= 0 || index >= workflow.nodes.length - 1 || target <= 0 || target >= workflow.nodes.length - 1) return workflow; const nodes = [...workflow.nodes]; [nodes[index], nodes[target]] = [nodes[target], nodes[index]]; return bump(connectSequentially({ ...workflow, nodes })); }
export function updateWorkflowNode(workflow: Workflow, nodeId: string, patch: Partial<WorkflowNode>): Workflow { return bump({ ...workflow, nodes: workflow.nodes.map((node) => node.id === nodeId ? { ...node, ...patch, id: node.id } : node) }); }
function bump(workflow: Workflow): Workflow { return { ...workflow, version: workflow.version + 1, updatedAt: new Date().toISOString() }; }

