import { validateWorkflow } from "./workflowValidation";
import type { Workflow, WorkflowRun, WorkflowTimelineEvent } from "./types";
export interface WorkflowRuntimeAdapter { mock: (nodeId: string) => Promise<void>; dryRun: (nodeId: string) => void }
export async function runWorkflow(workflow: Workflow, mode: "mock" | "dryRun", runtime: WorkflowRuntimeAdapter, deps: { now?: () => string; nextId?: () => string } = {}): Promise<WorkflowRun> {
  const issues = validateWorkflow(workflow); const now = deps.now ?? (() => new Date().toISOString()); const nextId = deps.nextId ?? (() => crypto.randomUUID()); const startedAt=now();
  const report=(patch:Partial<WorkflowRun>):WorkflowRun=>({ id: nextId(), workflowId: workflow.id, mode, status:"completed", realityMode:"Simulated", createdAt:startedAt, completedAt:now(), durationMs:0, input:{ workflowName:workflow.name.en, mode }, output:"Local workflow simulation report", errors:[], deliverableIds:[], evidenceIds:[], limitations:["No connected provider or external write was executed."], nextAction:"Review the simulated steps and perform required real-world actions manually.", events:[], validationCodes:[], ...patch });
  if (issues.some((issue) => issue.severity === "error")) return report({ status: "failed", output:"Validation failed before simulation.", errors:issues.map((issue)=>issue.code), validationCodes: issues.map((issue) => issue.code) });
  const events: WorkflowTimelineEvent[] = [];
  for (const node of workflow.nodes) { if (node.type === "approval") { events.push({ id: nextId(), nodeId: node.id, nodeType: node.type, status: "waitingForApproval", result:"waitingForApproval", timestamp: now(), summary: "Workflow paused for explicit local approval." }); return report({ status: "waitingForApproval", realityMode:"Manual action required", output:"Paused before the approval step.", nextAction:"Record the required human approval, then start a new local simulation.", events }); } if (node.type === "mockRun" && mode === "mock") await runtime.mock(node.id); if ((node.type === "dryRun" || node.type === "mockRun") && mode === "dryRun") runtime.dryRun(node.id); events.push({ id: nextId(), nodeId: node.id, nodeType: node.type, status: "completed", result:mode==="mock"?"simulated":"planned", timestamp: now(), summary: `${node.type} ${mode==="mock"?"simulated":"planned"} locally; no external action was executed.` }); }
  return report({ events, output:`${events.length} local steps recorded as ${mode==="mock"?"simulated":"planned"}.` });
}

