export const qaUi = {
  he: {
    releaseHeader: "מצב הבשלה לשחרור",
    version: "גרסה",
    environment: "סביבה",
    lastValidated: "בדיקה אחרונה",
    commit: "קומיט",
    branch: "ענף",
    notAvailable: "לא זמין",
    status: {
      ready: "מוכן",
      readyWithWarnings: "מוכן עם אזהרות",
      blocked: "חסום",
      notEvaluated: "טרם נבדק",
    },
    gate: {
      lint: "לינט",
      unitTests: "בדיקות יחידה/רכיב",
      coverage: "כיסוי קוד",
      build: "בנייה",
      e2eFast: "E2E מהיר",
      e2eFull: "E2E מלא",
      accessibility: "נגישות",
      visual: "רגרסיה ויזואלית",
      performance: "ביצועים",
      gitDiff: "בדיקת Git diff",
    },
    gateStatus: {
      passed: "עבר",
      failed: "נכשל",
      warning: "אזהרה",
      notRun: "לא הורץ",
      notAvailable: "לא זמין",
    },
    section: {
      gates: "שערי איכות",
      tests: "סיכום בדיקות",
      coverage: "כיסוי קוד",
      accessibility: "נגישות",
      visual: "רגרסיה ויזואלית",
      performance: "ביצועים",
      knownIssues: "בעיות ידועות וחוב טכני",
      analyzer: "סיכום ניתוח",
      checklist: "רשימת בדיקה לשחרור",
      issues: "מעקב בעיות פנימי",
    },
    source: {
      imported: "דוח שיובא ידנית",
      generated: "דוח מקומי שנוצר",
      sample: "נתוני דוגמה",
      none: "אין תוצאה זמינה",
      noneDescription:
        "לא נמצא דוח איכות מקומי או מ-CI. אפשר לייבא קובץ JSON שנוצר על ידי quality:collect, או לטעון נתוני דוגמה להדגמה.",
      loadSample: "טעינת נתוני דוגמה",
      clearSample: "הסרת נתוני הדוגמה",
      importButton: "ייבוא דוח JSON",
      clearImport: "ביטול הדוח המיובא",
      invalidReport: "קובץ הדוח אינו תקין",
      unsupportedSchema: "גרסת הסכימה של הדוח אינה נתמכת",
      generatedAt: "נוצר בתאריך",
      staleVersionWarning: "גרסת האפליקציה בדוח אינה תואמת את הגרסה הנוכחית.",
      staleCommitWarning: "הקומיט בדוח אינו תואם את הבנייה הנוכחית.",
      staleOldWarning: "הדוח ישן מהסף המתועד ועשוי לא לשקף את המצב הנוכחי.",
    },
    tests: {
      vitestLabel: "Vitest",
      playwrightLabel: "Playwright",
      total: "סה״כ",
      failed: "נכשלו",
      skipped: "דולגו",
      browserProjects: "פרויקטי דפדפן",
      duration: "משך ריצה",
      notAvailable: "אין נתוני בדיקות זמינים",
    },
    coverage: {
      statements: "הוראות",
      branches: "ענפים",
      functions: "פונקציות",
      lines: "שורות",
      threshold: "סף",
      trend: "מגמה",
      trendUnavailable: "מגמת היסטוריה עדיין אינה זמינה",
      notAvailable: "אין נתוני כיסוי זמינים",
    },
    a11y: {
      scannedPages: "עמודים שנסרקו",
      critical: "קריטי",
      serious: "חמור",
      moderate: "בינוני",
      minor: "קל",
      allowedIssues: "חריגים מתועדים",
      manualReview: "בדיקה ידנית",
      manualReviewComplete: "הושלמה",
      manualReviewIncomplete: "לא הושלמה",
      manualReviewNotStarted: "לא התחילה",
      notAvailable: "אין נתוני נגישות זמינים",
      disclaimer:
        "בדיקות אוטומטיות אינן מחליפות בדיקת מקלדת, קורא מסך, זום ובדיקת שימושיות קוגניטיבית — ראו את רשימת הבדיקה הידנית.",
    },
    visual: {
      baselineCount: "בסיסי השוואה",
      compared: "הושוו",
      mismatches: "אי-התאמות",
      environment: "סביבת בסיס",
      lastUpdate: "עדכון בסיס אחרון",
      notAvailable: "אין נתוני רגרסיה ויזואלית זמינים",
    },
    performance: {
      route: "נתיב",
      device: "מכשיר",
      desktop: "מחשב",
      mobile: "נייד",
      lcp: "LCP",
      cls: "CLS",
      tbt: "TBT",
      thresholdsDesktop: "ספי מחשב",
      thresholdsMobile: "ספי נייד",
      notAvailable: "אין נתוני ביצועים זמינים",
      disclaimer:
        "תוצאות Lighthouse הן נתוני מעבדה בלבד, נמדדות על חומרה מקומית או של CI, ואינן מקבילות לנתוני משתמשים אמיתיים.",
    },
    knownIssues: {
      openCount: "בעיות פתוחות",
      bySeverity: "לפי חומרה",
    },
    issues: {
      title: "מעקב בעיות פנימי (מקומי בדפדפן)",
      localNotice: "הרשימה נשמרת בדפדפן זה בלבד ואינה מסונכרנת עם מערכת חיצונית.",
      create: "בעיה חדשה",
      edit: "עריכה",
      resolve: "סימון כטופל",
      reopen: "פתיחה מחדש",
      delete: "מחיקה",
      deleteConfirmTitle: "מחיקת בעיה?",
      deleteConfirmDescription: "הפעולה תמחק את הבעיה מהמעקב המקומי ולא ניתן לבטל אותה.",
      cancel: "ביטול",
      save: "שמירה",
      required: "שדה חובה",
      search: "חיפוש בעיות",
      filterSeverity: "חומרה",
      filterStatus: "סטטוס",
      filterType: "סוג",
      all: "הכול",
      export: "ייצוא JSON",
      import: "ייבוא JSON",
      importInvalid: "חלק מהרשומות בקובץ אינן תקינות ולא יובאו",
      importSummary: "יובאו {accepted} בעיות, {rejected} נדחו",
      empty: "אין בעיות רשומות",
      noResults: "לא נמצאו בעיות תואמות",
      fieldTitle: "כותרת",
      fieldDescription: "תיאור",
      fieldType: "סוג",
      fieldSeverity: "חומרה",
      fieldOwner: "אחראי",
      fieldSource: "מקור",
      fieldTargetVersion: "גרסת יעד",
      fieldRelatedRoute: "נתיב קשור",
      fieldRelatedTest: "בדיקה קשורה",
      fieldNotes: "הערות",
    },
    issueType: {
      bug: "באג",
      accessibility: "נגישות",
      performance: "ביצועים",
      visual: "ויזואלי",
      automation: "אוטומציה",
      technicalDebt: "חוב טכני",
    },
    severity: {
      critical: "קריטי",
      high: "גבוה",
      medium: "בינוני",
      low: "נמוך",
    },
    issueStatus: {
      open: "פתוח",
      inProgress: "בטיפול",
      resolved: "טופל",
      acceptedRisk: "סיכון מקובל",
    },
    checklist: {
      title: "רשימת בדיקה לקראת שחרור",
      versionNotice: "הרשימה מוצגת עבור גרסה {version} ומתאפסת בכל עדכון גרסה.",
      automatedSection: "שערים אוטומטיים",
      manualSection: "בדיקות ידניות",
      automated: {
        lint: "לינט עבר",
        unitTests: "בדיקות יחידה עברו",
        coverage: "כיסוי עבר",
        build: "בנייה עברה",
        e2eFast: "E2E מהיר עבר",
        e2eFull: "E2E מלא עבר",
        accessibility: "נגישות עברה",
        visual: "בדיקה ויזואלית הושלמה",
        performance: "ביצועים עברו",
      },
      manual: {
        hebrewDesktop: "נבדק בעברית במחשב",
        englishDesktop: "נבדק באנגלית במחשב",
        hebrewMobile: "נבדק בעברית בנייד",
        englishMobile: "נבדק באנגלית בנייד",
        keyboardNav: "ניווט מקלדת נבדק",
        refreshRoutes: "רענון דפדפן בכל נתיב נבדק",
        exports: "ייצואים נבדקו",
        typography: "אין פגמי טיפוגרפיה נראים לעין",
        overlap: "אין חפיפה נראית לעין",
        consoleErrors: "אין שגיאות קונסול בלתי צפויות",
        releaseNotes: "הערות השחרור נסקרו",
      },
    },
    analyzer: {
      title: "סיכום ניתוח (חוקים דטרמיניסטיים, לא AI)",
      recommendedActions: "פעולות מומלצות",
      likelyAffectedAreas: "אזורים שסביר שהושפעו",
      noneDetected: "לא זוהו בעיות",
    },
  },
  en: {
    releaseHeader: "Release readiness",
    version: "Version",
    environment: "Environment",
    lastValidated: "Last validated",
    commit: "Commit",
    branch: "Branch",
    notAvailable: "Not available",
    status: {
      ready: "Ready",
      readyWithWarnings: "Ready with warnings",
      blocked: "Blocked",
      notEvaluated: "Not evaluated",
    },
    gate: {
      lint: "Lint",
      unitTests: "Unit/Component tests",
      coverage: "Coverage",
      build: "Build",
      e2eFast: "E2E fast",
      e2eFull: "E2E full",
      accessibility: "Accessibility",
      visual: "Visual regression",
      performance: "Performance",
      gitDiff: "Git diff check",
    },
    gateStatus: {
      passed: "Passed",
      failed: "Failed",
      warning: "Warning",
      notRun: "Not run",
      notAvailable: "Not available",
    },
    section: {
      gates: "Quality gates",
      tests: "Test summary",
      coverage: "Coverage",
      accessibility: "Accessibility",
      visual: "Visual regression",
      performance: "Performance",
      knownIssues: "Known issues and technical debt",
      analyzer: "Analyzer summary",
      checklist: "Release readiness checklist",
      issues: "Internal issue register",
    },
    source: {
      imported: "Manually imported report",
      generated: "Locally generated report",
      sample: "Sample data",
      none: "No result available",
      noneDescription:
        "No local or CI-generated quality report was found. Import a JSON file produced by quality:collect, or load sample data for a preview.",
      loadSample: "Load sample data",
      clearSample: "Clear sample data",
      importButton: "Import report JSON",
      clearImport: "Clear imported report",
      invalidReport: "The report file is not valid",
      unsupportedSchema: "The report's schema version is not supported",
      generatedAt: "Generated at",
      staleVersionWarning: "The report's application version does not match the current version.",
      staleCommitWarning: "The report's commit does not match the current build.",
      staleOldWarning: "This report is older than the documented threshold and may not reflect the current state.",
    },
    tests: {
      vitestLabel: "Vitest",
      playwrightLabel: "Playwright",
      total: "Total",
      failed: "Failed",
      skipped: "Skipped",
      browserProjects: "Browser projects",
      duration: "Duration",
      notAvailable: "No test data available",
    },
    coverage: {
      statements: "Statements",
      branches: "Branches",
      functions: "Functions",
      lines: "Lines",
      threshold: "Threshold",
      trend: "Trend",
      trendUnavailable: "Trend history is not available yet",
      notAvailable: "No coverage data available",
    },
    a11y: {
      scannedPages: "Scanned pages",
      critical: "Critical",
      serious: "Serious",
      moderate: "Moderate",
      minor: "Minor",
      allowedIssues: "Documented allowed issues",
      manualReview: "Manual review",
      manualReviewComplete: "Complete",
      manualReviewIncomplete: "Incomplete",
      manualReviewNotStarted: "Not started",
      notAvailable: "No accessibility data available",
      disclaimer:
        "Automated scans do not replace keyboard-only, screen-reader, zoom, or cognitive usability review — see the manual QA checklist.",
    },
    visual: {
      baselineCount: "Baselines",
      compared: "Compared",
      mismatches: "Mismatches",
      environment: "Baseline environment",
      lastUpdate: "Last baseline update",
      notAvailable: "No visual regression data available",
    },
    performance: {
      route: "Route",
      device: "Device",
      desktop: "Desktop",
      mobile: "Mobile",
      lcp: "LCP",
      cls: "CLS",
      tbt: "TBT",
      thresholdsDesktop: "Desktop thresholds",
      thresholdsMobile: "Mobile thresholds",
      notAvailable: "No performance data available",
      disclaimer:
        "Lighthouse results are lab data only, measured on local or CI hardware, and are not equivalent to real-user field data.",
    },
    knownIssues: {
      openCount: "Open issues",
      bySeverity: "By severity",
    },
    issues: {
      title: "Internal issue register (browser-local)",
      localNotice: "This list is stored only in this browser and is not synced to any external system.",
      create: "New issue",
      edit: "Edit",
      resolve: "Resolve",
      reopen: "Reopen",
      delete: "Delete",
      deleteConfirmTitle: "Delete this issue?",
      deleteConfirmDescription: "This removes the issue from the local register and cannot be undone.",
      cancel: "Cancel",
      save: "Save",
      required: "This field is required",
      search: "Search issues",
      filterSeverity: "Severity",
      filterStatus: "Status",
      filterType: "Type",
      all: "All",
      export: "Export JSON",
      import: "Import JSON",
      importInvalid: "Some entries in the file were invalid and were not imported",
      importSummary: "Imported {accepted} issues, {rejected} rejected",
      empty: "No issues recorded",
      noResults: "No issues match these filters",
      fieldTitle: "Title",
      fieldDescription: "Description",
      fieldType: "Type",
      fieldSeverity: "Severity",
      fieldOwner: "Owner",
      fieldSource: "Source",
      fieldTargetVersion: "Target version",
      fieldRelatedRoute: "Related route",
      fieldRelatedTest: "Related test",
      fieldNotes: "Notes",
    },
    issueType: {
      bug: "Bug",
      accessibility: "Accessibility",
      performance: "Performance",
      visual: "Visual",
      automation: "Automation",
      technicalDebt: "Technical debt",
    },
    severity: {
      critical: "Critical",
      high: "High",
      medium: "Medium",
      low: "Low",
    },
    issueStatus: {
      open: "Open",
      inProgress: "In progress",
      resolved: "Resolved",
      acceptedRisk: "Accepted risk",
    },
    checklist: {
      title: "Release readiness checklist",
      versionNotice: "This checklist applies to version {version} and resets on every version bump.",
      automatedSection: "Automated gates",
      manualSection: "Manual checks",
      automated: {
        lint: "Lint passed",
        unitTests: "Unit tests passed",
        coverage: "Coverage passed",
        build: "Build passed",
        e2eFast: "E2E fast passed",
        e2eFull: "E2E full passed",
        accessibility: "Accessibility passed",
        visual: "Visual review completed",
        performance: "Performance passed",
      },
      manual: {
        hebrewDesktop: "Hebrew desktop reviewed",
        englishDesktop: "English desktop reviewed",
        hebrewMobile: "Hebrew mobile reviewed",
        englishMobile: "English mobile reviewed",
        keyboardNav: "Keyboard navigation reviewed",
        refreshRoutes: "Browser refresh on routes reviewed",
        exports: "Exports reviewed",
        typography: "No obvious typography defects",
        overlap: "No visible overlap",
        consoleErrors: "No unexpected console errors",
        releaseNotes: "Release notes reviewed",
      },
    },
    analyzer: {
      title: "Analyzer summary (deterministic rules, not AI)",
      recommendedActions: "Recommended actions",
      likelyAffectedAreas: "Likely affected areas",
      noneDetected: "No issues detected",
    },
  },
} as const

export type QaUiLanguage = keyof typeof qaUi
