import type { ExecutionMode, RunStatus } from "./types";
export const runtimeUi = {
  en: {
    runtime: "Runtime",
    history: "Run History",
    description: "Inspect browser-local Mock and Dry Run records.",
    privacy: "Browser-local only. Do not enter sensitive information.",
    count: "Runs",
    search: "Search",
    mode: "Mode",
    status: "Status",
    provider: "Provider",
    all: "All",
    clearFilters: "Clear filters",
    clearHistory: "Clear history",
    clearConfirm: "Clear all local Runtime history?",
    delete: "Delete run",
    deleteConfirm: "Delete this local Runtime run?",
    cancel: "Cancel",
    confirm: "Confirm",
    noRuns: "No runs yet",
    demo: "Runtime demo",
    demoNotice: "QA learning controls — not a final production workflow.",
    mockSuccess: "Mock success",
    mockRetry: "Mock retry",
    mockRetryFail: "Mock retry exhausted",
    mockApproval: "Mock approval",
    mockCancel: "Mock cancel",
    dryRun: "Dry Run",
    liveRun: "Live Run",
    liveDisabled: "Live execution is not available in Version 1.2.0-beta.1.",
    simulated: "Simulated Mock output — no external service was called.",
    dryLabel: "Dry Run preview — no provider or external tool was executed.",
    plannedTools: "Planned Tools",
    notConnected: "Planned tool only — not connected.",
    approvalRequired: "Approval Required",
    waitingApproval: "Waiting for approval",
    approve: "Approve local simulation",
    reject: "Reject and cancel",
    retry: "Retry",
    attempts: "Attempts",
    validation: "Validation",
    timeline: "Timeline",
    warnings: "Warnings",
    output: "Output",
    request: "Request summary",
    back: "Back to Run History",
    notFound: "Run not found",
    notFoundText: "This local Runtime record does not exist.",
    noTools: "No external tools were executed",
    help: "Runtime help",
    storageWarning: "Runtime storage warning",
  },
  he: {
    runtime: "מנוע הרצה",
    history: "היסטוריית הרצות",
    description: "צפייה בהרצות Mock ובתצוגות Dry Run שנשמרו בדפדפן.",
    privacy: "נשמר בדפדפן המקומי בלבד. אין להזין מידע רגיש.",
    count: "הרצות",
    search: "חיפוש",
    mode: "מצב",
    status: "סטטוס",
    provider: "ספק",
    all: "הכול",
    clearFilters: "ניקוי מסננים",
    clearHistory: "ניקוי היסטוריה",
    clearConfirm: "לנקות את כל היסטוריית ההרצות המקומית?",
    delete: "מחיקת הרצה",
    deleteConfirm: "למחוק את ההרצה המקומית הזו?",
    cancel: "ביטול",
    confirm: "אישור",
    noRuns: "עדיין אין הרצות",
    demo: "הדגמת Runtime",
    demoNotice: "כלי לימודי ל-QA — לא תהליך עבודה סופי.",
    mockSuccess: "הרצת Mock מוצלחת",
    mockRetry: "ניסיון חוזר ב-Mock",
    mockRetryFail: "כשל לאחר ניסיונות",
    mockApproval: "Mock עם אישור",
    mockCancel: "ביטול Mock",
    dryRun: "Dry Run",
    liveRun: "הרצה חיה",
    liveDisabled: "הרצה חיה אינה זמינה בגרסה 1.2.0-beta.1.",
    simulated: "פלט Mock מדומה — לא הופעל שירות חיצוני.",
    dryLabel: "תצוגת Dry Run — לא הופעל ספק AI ולא הופעל כלי חיצוני.",
    plannedTools: "כלים מתוכננים",
    notConnected: "כלי מתוכנן בלבד — לא מחובר.",
    approvalRequired: "נדרש אישור",
    waitingApproval: "ממתין לאישור",
    approve: "אישור סימולציה מקומית",
    reject: "דחייה וביטול",
    retry: "ניסיון חוזר",
    attempts: "ניסיונות",
    validation: "אימות",
    timeline: "ציר זמן",
    warnings: "אזהרות",
    output: "פלט",
    request: "סיכום בקשה",
    back: "חזרה להיסטוריית הרצות",
    notFound: "ההרצה לא נמצאה",
    notFoundText: "רשומת ה-Runtime המקומית אינה קיימת.",
    noTools: "לא הופעלו כלים חיצוניים",
    help: "עזרה בנושא Runtime",
    storageWarning: "אזהרת אחסון Runtime",
  },
} as const;
export const statusLabels: Record<"en" | "he", Record<RunStatus, string>> = {
  en: {
    draft: "Draft",
    queued: "Queued",
    running: "Running",
    waitingForApproval: "Waiting for approval",
    retrying: "Retrying",
    completed: "Completed",
    failed: "Failed",
    cancelled: "Cancelled",
  },
  he: {
    draft: "טיוטה",
    queued: "בתור",
    running: "רץ",
    waitingForApproval: "ממתין לאישור",
    retrying: "ניסיון חוזר",
    completed: "הושלם",
    failed: "נכשל",
    cancelled: "בוטל",
  },
};
export const modeLabels: Record<"en" | "he", Record<ExecutionMode, string>> = {
  en: { mock: "Mock Run", dryRun: "Dry Run", liveReserved: "Live Run" },
  he: { mock: "הרצת Mock", dryRun: "Dry Run", liveReserved: "הרצה חיה" },
};

const hebrewRuntimeText: Record<string, string> = {
  "Mock run queued.": "הרצת Mock נוספה לתור.",
  "Mock Provider started locally.": "ספק Mock התחיל לפעול מקומית.",
  "The Mock run completed.": "הרצת Mock הושלמה.",
  "A deterministic retry was scheduled.": "נקבע ניסיון חוזר דטרמיניסטי.",
  "Mock retry started.": "ניסיון Mock חוזר התחיל.",
  "The Mock retry completed.": "ניסיון Mock חוזר הושלם.",
  "Retry attempts were exhausted.": "מכסת הניסיונות החוזרים הסתיימה.",
  "Mock run failed after retry exhaustion.":
    "הרצת Mock נכשלה לאחר מיצוי הניסיונות.",
  "Run is waiting for explicit approval.": "ההרצה ממתינה לאישור מפורש.",
  "Approval granted for this local run only.":
    "ניתן אישור להרצה המקומית הזו בלבד.",
  "Approved Mock simulation completed.": "סימולציית Mock המאושרת הושלמה.",
  "Approval rejected; the run was cancelled.": "האישור נדחה וההרצה בוטלה.",
  "Mock scenario requested cancellation.": "תרחיש Mock ביקש ביטול.",
  "Dry Run preview completed locally.": "תצוגת Dry Run הושלמה מקומית.",
  "Output is simulated; no external service was called.":
    "הפלט מדומה; לא הופעל שירות חיצוני.",
  "Output is simulated.": "הפלט מדומה.",
  "No external tool will be executed.": "לא יופעל כלי חיצוני.",
};
export function localizeRuntimeText(ui: "he" | "en", value: string) {
  return ui === "he" ? (hebrewRuntimeText[value] ?? value) : value;
}
