export const catalogUi = {
  he: {
    myPrompts: "הפרומפטים שלי",
    catalog: "קטלוג התחלתי",
    title: "קטלוג פרומפטים התחלתי",
    description:
      "פרומפטים לקריאה בלבד שנבדקו להכללה חינוכית. ייבוא יוצר עותק מקומי וניתן לעריכה.",
    source: "מקור",
    license: "רישיון",
    import: "ייבוא לספרייה",
    imported: "כבר יובא",
    openCopy: "פתיחת העותק שלי",
    preview: "תצוגה מקדימה",
    results: "תוצאות",
    noResults: "לא נמצאו פרומפטים תואמים",
    noAffiliation:
      "האקדמיה של שבי אינה קשורה ל-prompts.chat ואינה מאושרת על ידה.",
    another: "ייבוא עותק נוסף",
    cancel: "ביטול",
    duplicateTitle: "הפרומפט כבר יובא",
    duplicateText:
      "קיים עותק מקומי. אפשר לפתוח אותו או ליצור עותק נוסף במפורש.",
    search: "חיפוש בקטלוג",
    category: "קטגוריה",
    language: "שפה",
    sort: "מיון",
    clear: "ניקוי מסננים",
    all: "הכול",
    copy: "העתקת טקסט",
    copied: "הטקסט הועתק",
    help: "עזרה",
  },
  en: {
    myPrompts: "My Prompts",
    catalog: "Starter Catalog",
    title: "Starter Prompt Catalog",
    description:
      "Read-only prompts reviewed for educational inclusion. Importing creates an editable local copy.",
    source: "Source",
    license: "License",
    import: "Import to Library",
    imported: "Already imported",
    openCopy: "Open my copy",
    preview: "Preview",
    results: "Results",
    noResults: "No matching prompts found",
    noAffiliation:
      "Shabi's AI Academy is not affiliated with or endorsed by prompts.chat.",
    another: "Import another copy",
    cancel: "Cancel",
    duplicateTitle: "Prompt already imported",
    duplicateText:
      "A local copy exists. Open it, or explicitly create another copy.",
    search: "Search Catalog",
    category: "Category",
    language: "Language",
    sort: "Sort by",
    clear: "Clear filters",
    all: "All",
    copy: "Copy prompt text",
    copied: "Prompt text copied",
    help: "Help",
  },
} as const;
