import { useState, type FormEvent } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import { safeRequestedRoute, useAuth, validEmail } from "../../auth";
import { AuthCard } from "../../components/auth/AuthCard";
import { useLanguage } from "../../i18n/LanguageContext";
export function AuthLoginPage() {
  const { language } = useLanguage(); const { isConfigured, status, signIn, sendMagicLink, continueAsGuest } = useAuth(); const location = useLocation(); const navigate = useNavigate();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [show, setShow] = useState(false); const [message, setMessage] = useState("");
  const destination = safeRequestedRoute(new URLSearchParams(location.search).get("from")); const pending = status === "loading";
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!validEmail(email) || !password) { setMessage(language === "he" ? "בדקו את כתובת הדוא״ל והסיסמה." : "Check your email address and password."); return; } const result = await signIn(email, password); if (result.ok) navigate(destination, { replace: true }); else setMessage(language === "he" ? "לא ניתן להיכנס. בדקו את הפרטים או נסו שוב." : "Unable to sign in. Check your details or try again."); };
  const magic = async () => { if (!validEmail(email)) { setMessage(language === "he" ? "הזינו כתובת דוא״ל תקינה." : "Enter a valid email address."); return; } try { sessionStorage.setItem("shabis-ai-academy-auth-destination", destination); } catch { /* Requested-route persistence is optional. */ } const result = await sendMagicLink(email); setMessage(result.ok ? (language === "he" ? "אם החשבון זמין, קישור כניסה נשלח." : "If the account is available, a sign-in link was sent.") : (language === "he" ? "לא ניתן לשלוח קישור כעת." : "A link cannot be sent right now.")); };
  return <AuthCard title={language === "he" ? "כניסה לחשבון" : "Sign in"} description={language === "he" ? "התחברו לסנכרון אופציונלי, או המשיכו מקומית כאורחים." : "Sign in for optional sync, or continue locally as Guest."}><form className="auth-form" onSubmit={submit}><label>{language === "he" ? "דוא״ל" : "Email"}<input type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} disabled={!isConfigured || pending} /></label><label>{language === "he" ? "סיסמה" : "Password"}<span className="password-field"><input type={show ? "text" : "password"} autoComplete="current-password" value={password} onChange={(event) => setPassword(event.target.value)} disabled={!isConfigured || pending} /><button type="button" onClick={() => setShow((value) => !value)}>{show ? (language === "he" ? "הסתר" : "Hide") : (language === "he" ? "הצג" : "Show")}</button></span></label><p className="form-help">{language === "he" ? "ההתחברות נשמרת באופן מאובטח בידי ספק האימות בדפדפן זה." : "Your session is securely managed by the auth provider in this browser."}</p>{message && <p role="status">{message}</p>}<button className="button button-primary" type="submit" disabled={!isConfigured || pending}>{pending ? (language === "he" ? "נכנסים…" : "Signing in…") : (language === "he" ? "כניסה" : "Sign in")}</button><button className="button button-secondary" type="button" onClick={magic} disabled={!isConfigured || pending}>{language === "he" ? "שלחו קישור כניסה" : "Send Magic Link"}</button></form><div className="auth-links"><Link to="/auth/forgot-password">{language === "he" ? "שכחתי סיסמה" : "Forgot password"}</Link><Link to="/auth/register">{language === "he" ? "יצירת חשבון" : "Create account"}</Link></div><button className="guest-button" type="button" onClick={() => { continueAsGuest(); navigate(destination, { replace: true }); }}>{language === "he" ? "המשך כאורח" : "Continue as Guest"}</button></AuthCard>;
}
