import { useState, type FormEvent } from "react";
import { Link, useNavigate } from "react-router-dom";
import { passwordIssues, useAuth, validEmail } from "../../auth";
import { AuthCard } from "../../components/auth/AuthCard";
import { useLanguage } from "../../i18n/LanguageContext";
export function AuthRegisterPage() {
  const { language } = useLanguage(); const { isConfigured, register, status } = useAuth(); const navigate = useNavigate(); const [message, setMessage] = useState("");
  const [form, setForm] = useState({ firstName: "", lastName: "", email: "", password: "", confirm: "", language, terms: false, privacy: false, experienceLevel: "", mainGoal: "" });
  const update = (name: string, value: string | boolean) => setForm((current) => ({ ...current, [name]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!form.firstName.trim() || !form.lastName.trim() || !validEmail(form.email) || passwordIssues(form.password).length || form.password !== form.confirm || !form.terms || !form.privacy) { setMessage(language === "he" ? "השלימו את כל השדות ובדקו את הסיסמה וההסכמות." : "Complete all fields and check the password and consent boxes."); return; } const result = await register(form); if (result.ok) navigate(result.requiresEmailVerification ? `/auth/verify-email?email=${encodeURIComponent(form.email)}` : "/onboarding", { replace: true }); else setMessage(language === "he" ? "לא ניתן ליצור חשבון. נסו שוב או היכנסו לחשבון קיים." : "Unable to create an account. Try again or sign in to an existing account."); };
  return <AuthCard title={language === "he" ? "יצירת חשבון" : "Create account"} description={language === "he" ? "צרו חשבון אופציונלי מבלי לאבד עבודה מקומית." : "Create an optional account without losing local work."}><form className="auth-form" onSubmit={submit}><div className="auth-name-grid"><label>{language === "he" ? "שם פרטי" : "First name"}<input autoComplete="given-name" value={form.firstName} onChange={(e) => update("firstName", e.target.value)} /></label><label>{language === "he" ? "שם משפחה" : "Last name"}<input autoComplete="family-name" value={form.lastName} onChange={(e) => update("lastName", e.target.value)} /></label></div><label>{language === "he" ? "דוא״ל" : "Email"}<input type="email" autoComplete="email" value={form.email} onChange={(e) => update("email", e.target.value)} /></label><label>{language === "he" ? "סיסמה" : "Password"}<input type="password" autoComplete="new-password" value={form.password} onChange={(e) => update("password", e.target.value)} aria-describedby="password-rules" /></label><p id="password-rules" className="form-help">{language === "he" ? "לפחות 10 תווים, אות גדולה, אות קטנה ומספר." : "At least 10 characters with upper case, lower case, and a number."}</p><label>{language === "he" ? "אימות סיסמה" : "Confirm password"}<input type="password" autoComplete="new-password" value={form.confirm} onChange={(e) => update("confirm", e.target.value)} /></label><label>{language === "he" ? "רמת ניסיון (רשות)" : "Experience level (optional)"}<select value={form.experienceLevel} onChange={(e) => update("experienceLevel", e.target.value)}><option value="">—</option><option value="beginner">Beginner</option><option value="intermediate">Intermediate</option><option value="advanced">Advanced</option></select></label><label>{language === "he" ? "מטרה עיקרית (רשות)" : "Main goal (optional)"}<input value={form.mainGoal} onChange={(e) => update("mainGoal", e.target.value)} /></label><label className="consent-row"><input type="checkbox" checked={form.terms} onChange={(e) => update("terms", e.target.checked)} />{language === "he" ? "אני מסכים/ה" : "I agree to the"} <Link to="/terms">{language === "he" ? "לתנאי השימוש" : "Terms"}</Link></label><label className="consent-row"><input type="checkbox" checked={form.privacy} onChange={(e) => update("privacy", e.target.checked)} />{language === "he" ? "קראתי את הודעת הפרטיות" : "I acknowledge the Privacy Notice"}</label>{message && <p role="alert">{message}</p>}<button className="button button-primary" disabled={!isConfigured || status === "loading"} type="submit">{status === "loading" ? (language === "he" ? "יוצרים…" : "Creating…") : (language === "he" ? "יצירת חשבון" : "Create account")}</button></form><Link to="/auth/login">{language === "he" ? "כבר יש לי חשבון" : "I already have an account"}</Link></AuthCard>;
}
