import { describe, expect, it } from "vitest";
import { applyWorkspaceImport, backupDomainKeys, checksumPayload, createWorkspaceBackup, previewWorkspaceImport, serializeWorkspaceBackup } from ".";
function memoryStorage(seed: Record<string,string> = {}, failKey = "") { const map = new Map(Object.entries(seed)); return { getItem: (key: string) => map.get(key) ?? null, setItem: (key: string, value: string) => { if (key === failKey) throw new Error("quota"); map.set(key, value); }, removeItem: (key: string) => { map.delete(key); }, map }; }
describe("complete Workspace backup", () => {
  it("exports whitelisted parsed domains with metadata and checksum", () => { const storage = memoryStorage({ [backupDomainKeys.prompts]: JSON.stringify({ schemaVersion: 1, prompts: [{ id: "p1" }] }), [backupDomainKeys.settings]: "en", unrelated: "secret" }); const backup = createWorkspaceBackup(storage, () => "now"); expect(backup.domains.prompts).toBeDefined(); expect(backup.domains.settings).toBe("en"); expect(JSON.stringify(backup)).not.toContain("unrelated"); expect(backup.checksum).toBe(checksumPayload({ schemaVersion: 1, appVersion: "1.1.0-beta.1", exportedAt: "now", domainVersions: backup.domainVersions, domains: backup.domains })); });
  it("previews conflicts and applies merge or replace per domain", () => { const storage = memoryStorage({ [backupDomainKeys.prompts]: JSON.stringify({ schemaVersion: 1, prompts: [{ id: "p1", title: "old" }] }) }); const backup = createWorkspaceBackup(memoryStorage({ [backupDomainKeys.prompts]: JSON.stringify({ schemaVersion: 1, prompts: [{ id: "p1", title: "new" }, { id: "p2" }] }) })); const preview = previewWorkspaceImport(serializeWorkspaceBackup(backup), storage); expect(preview.valid).toBe(true); expect(preview.domains[0].conflicts).toBe(1); const report = applyWorkspaceImport(preview, { prompts: "merge" }, storage); expect(report.ok).toBe(true); expect(JSON.parse(storage.getItem(backupDomainKeys.prompts)!).prompts).toHaveLength(2); });
  it("rejects malformed, oversized, secret-bearing, and modified imports", () => { expect(previewWorkspaceImport("{").errors).toContain("malformed-json"); expect(previewWorkspaceImport("x".repeat(8_000_001)).errors).toContain("oversized-import"); const backup = createWorkspaceBackup(memoryStorage()); const secret = { ...backup, domains: { workspace: { apiKey: "no" } } }; secret.checksum = checksumPayload({ schemaVersion: secret.schemaVersion, appVersion: secret.appVersion, exportedAt: secret.exportedAt, domainVersions: secret.domainVersions, domains: secret.domains }); expect(previewWorkspaceImport(JSON.stringify(secret)).errors).toContain("secret-shaped-key"); const changed = { ...backup, appVersion: "changed" }; expect(previewWorkspaceImport(JSON.stringify(changed)).errors).toContain("checksum-mismatch"); });
  it("rolls back every touched key after a write failure", () => { const source = memoryStorage({ [backupDomainKeys.prompts]: JSON.stringify({ prompts: [{ id: "new" }] }), [backupDomainKeys.agents]: JSON.stringify({ agents: [{ id: "a" }] }) }); const preview = previewWorkspaceImport(serializeWorkspaceBackup(createWorkspaceBackup(source))); const target = memoryStorage({ [backupDomainKeys.prompts]: "old" }, backupDomainKeys.agents); const report = applyWorkspaceImport(preview, { prompts: "replace", agents: "replace" }, target); expect(report.rolledBack).toBe(true); expect(target.getItem(backupDomainKeys.prompts)).toBe("old"); });
});
