import type { BackupDomain, WorkspaceBackup } from "./types";
import { outcomeStorageKey } from "../outcomes/repository";
export const BACKUP_MAX_BYTES = 8_000_000;
export const backupDomainKeys: Record<BackupDomain, string> = {
  settings: "shabis-ai-academy-language", courseProgress: "shabi-ai-academy.course-progress.v1", prompts: "shabi-ai-academy.prompt-library.v1", agents: "shabi-ai-academy.agent-library.v1", projects: "shabis-ai-academy.projects.v1", knowledge: "shabis-ai-academy.knowledge.v1", workflows: "shabis-ai-academy:workflows:v1", runHistory: "shabis-ai-academy.runtime.runs.v1", promptPlayground: "shabis-ai-academy.playground.prompts.v1", agentPlayground: "shabis-ai-academy.playground.agents.v1", assistantHistory: "shabis-ai-academy:assistant:v1", workspace: "shabis-ai-academy:workspace:v1", searchHistory: "shabis-ai-academy:search:v1", commandHistory: "shabis-ai-academy:commands:v1",
  missions: "shabis-ai-academy:missions:v1:local-guest", agentTeams: "shabis-ai-academy:agent-teams:v1:local-guest", skillMap: "shabis-ai-academy:skill-map:v1:local-guest", contextPacks: "shabis-ai-academy:context-packs:v1:local-guest", missionAnalytics: "shabis-ai-academy:mission-analytics:v1:local-guest",
  evaluationRubrics: "shabis-ai-academy:evaluation-rubrics:v1:local-guest", evaluationExperiments: "shabis-ai-academy:evaluation-experiments:v1:local-guest", evaluationRuns: "shabis-ai-academy:evaluation-runs:v1:local-guest", evaluationSuites: "shabis-ai-academy:evaluation-suites:v1:local-guest", failureLibrary: "shabis-ai-academy:failure-library:v1:local-guest", entityVersions: "shabis-ai-academy:entity-versions:v1:local-guest", connectedPreviews: "shabis-ai-academy:connected-previews:v1:local-guest",
  evaluationEvidence: "shabis-ai-academy:evaluation-evidence:v1:local-guest", evaluationTraces: "shabis-ai-academy:evaluation-traces:v1:local-guest",
  outcomes: outcomeStorageKey("local-guest"),
};
export const normalizeBackupActorId = (actorId: string) => actorId.toLowerCase().replace(/[^a-z0-9._-]/g, "-").slice(0, 80) || "local-guest";
const resolveDomainKeys = (storage: Pick<Storage,"getItem">, actorId?: string): Record<BackupDomain,string> => {
  const actor = normalizeBackupActorId(actorId ?? storage.getItem("shabis-ai-academy:mission-actor:v1") ?? "local-guest");
  return { ...backupDomainKeys, missions: `shabis-ai-academy:missions:v1:${actor}`, agentTeams: `shabis-ai-academy:agent-teams:v1:${actor}`, skillMap: `shabis-ai-academy:skill-map:v1:${actor}`, contextPacks: `shabis-ai-academy:context-packs:v1:${actor}`, missionAnalytics: `shabis-ai-academy:mission-analytics:v1:${actor}`, evaluationRubrics: `shabis-ai-academy:evaluation-rubrics:v1:${actor}`, evaluationExperiments: `shabis-ai-academy:evaluation-experiments:v1:${actor}`, evaluationRuns: `shabis-ai-academy:evaluation-runs:v1:${actor}`, evaluationSuites: `shabis-ai-academy:evaluation-suites:v1:${actor}`, failureLibrary: `shabis-ai-academy:failure-library:v1:${actor}`, entityVersions: `shabis-ai-academy:entity-versions:v1:${actor}`, connectedPreviews: `shabis-ai-academy:connected-previews:v1:${actor}`, evaluationEvidence: `shabis-ai-academy:evaluation-evidence:v1:${actor}`, evaluationTraces: `shabis-ai-academy:evaluation-traces:v1:${actor}`, outcomes: outcomeStorageKey(actor) };
};
export function resolveBackupDomainKeys(storage: Pick<Storage,"getItem"> = localStorage, actorId?: string) { return resolveDomainKeys(storage, actorId); }
export function checksumPayload(value: unknown): string { const text = JSON.stringify(value); let hash = 0x811c9dc5; for (let index = 0; index < text.length; index += 1) { hash ^= text.charCodeAt(index); hash = Math.imul(hash, 0x01000193); } return `fnv1a-${(hash >>> 0).toString(16).padStart(8, "0")}`; }
const SECRET_KEY = /api.?key|secret|password|token|authorization|credential|private.?key/i;
const SECRET_VALUE = /(?:bearer\s+[a-z0-9._-]+|-----BEGIN [A-Z ]+PRIVATE KEY-----|(?:api[-_ ]?key|password|token|secret|credential)\s*[:=]\s*\S+|\bsk-[a-z0-9_-]{16,}\b|\bgh[pousr]_[a-z0-9]{20,}\b|\bAKIA[A-Z0-9]{16}\b|\b[a-z0-9_-]{10,}\.[a-z0-9_-]{10,}\.[a-z0-9_-]{10,}\b)/i;
const PRIVATE_PATH = /(?:\\\\[^\\\s]+\\[^\\\s]+|\b[a-z]:[\\/][^\s"']+|\/(?:users|home|private|root|etc|var|tmp|opt|srv)\/[^\s"']*)/i;
function secretLikeKey(value: unknown, depth = 0): boolean { if (depth > 30 || !value || typeof value !== "object") return false; if (Array.isArray(value)) return value.some((item) => secretLikeKey(item, depth + 1)); return Object.entries(value as Record<string, unknown>).some(([key, item]) => SECRET_KEY.test(key) || secretLikeKey(item, depth + 1)); }
function secretLikeValue(value: unknown, depth = 0): boolean { if (depth > 30) return true; if (typeof value === "string") return SECRET_VALUE.test(value) || PRIVATE_PATH.test(value); if (!value || typeof value !== "object") return false; if (Array.isArray(value)) return value.some((item) => secretLikeValue(item, depth + 1)); return Object.values(value as Record<string, unknown>).some((item) => secretLikeValue(item, depth + 1)); }
function parseDomain(domain: BackupDomain, raw: string): unknown { if (domain === "settings") return raw === "he" || raw === "en" ? raw : "he"; return JSON.parse(raw) as unknown; }
export function createWorkspaceBackup(storage: Pick<Storage,"getItem"> = localStorage, now = () => new Date().toISOString(), actorId?: string): WorkspaceBackup { const domains: Partial<Record<BackupDomain, unknown>> = {}; const safeActor = normalizeBackupActorId(actorId ?? storage.getItem("shabis-ai-academy:mission-actor:v1") ?? "local-guest"); const keys = resolveDomainKeys(storage, safeActor); for (const [domain, key] of Object.entries(keys) as Array<[BackupDomain,string]>) { const raw = storage.getItem(key); if (raw === null) continue; try { const parsed = parseDomain(domain, raw); if (!secretLikeKey(parsed) && !secretLikeValue(parsed)) domains[domain] = parsed; } catch { /* malformed or unsafe domains are excluded instead of exported */ } } const envelope = { schemaVersion: 3 as const, appVersion: "2.0.0", actorId: safeActor, exportedAt: now(), domainVersions: Object.fromEntries((Object.keys(keys) as BackupDomain[]).map((domain) => [domain, domain === "outcomes" ? 2 : 1])) as Record<BackupDomain,number>, domains }; return { ...envelope, checksum: checksumPayload(envelope) }; }
export function serializeWorkspaceBackup(backup: WorkspaceBackup): string { return JSON.stringify(backup, null, 2); }
export function containsSecretLikeKey(value: unknown): boolean { return secretLikeKey(value); }
export function containsSecretLikeValue(value: unknown): boolean { return secretLikeValue(value); }

