import type { BackupDomain, WorkspaceBackup } from "./types";
export const BACKUP_MAX_BYTES = 8_000_000;
export const backupDomainKeys: Record<BackupDomain, string> = {
  settings: "shabis-ai-academy-language", courseProgress: "shabi-ai-academy.course-progress.v1", prompts: "shabi-ai-academy.prompt-library.v1", agents: "shabi-ai-academy.agent-library.v1", projects: "shabis-ai-academy.projects.v1", knowledge: "shabis-ai-academy.knowledge.v1", workflows: "shabis-ai-academy:workflows:v1", runHistory: "shabis-ai-academy.runtime.runs.v1", promptPlayground: "shabis-ai-academy.playground.prompts.v1", agentPlayground: "shabis-ai-academy.playground.agents.v1", assistantHistory: "shabis-ai-academy:assistant:v1", workspace: "shabis-ai-academy:workspace:v1", searchHistory: "shabis-ai-academy:search:v1", commandHistory: "shabis-ai-academy:commands:v1",
};
export function checksumPayload(value: unknown): string { const text = JSON.stringify(value); let hash = 0x811c9dc5; for (let index = 0; index < text.length; index += 1) { hash ^= text.charCodeAt(index); hash = Math.imul(hash, 0x01000193); } return `fnv1a-${(hash >>> 0).toString(16).padStart(8, "0")}`; }
function secretLike(value: unknown, depth = 0): boolean { if (depth > 30 || !value || typeof value !== "object") return false; if (Array.isArray(value)) return value.some((item) => secretLike(item, depth + 1)); return Object.entries(value as Record<string, unknown>).some(([key, item]) => /api.?key|secret|password|token|authorization|credential/i.test(key) || secretLike(item, depth + 1)); }
function parseDomain(domain: BackupDomain, raw: string): unknown { if (domain === "settings") return raw === "he" || raw === "en" ? raw : "he"; return JSON.parse(raw) as unknown; }
export function createWorkspaceBackup(storage: Pick<Storage,"getItem"> = localStorage, now = () => new Date().toISOString()): WorkspaceBackup { const domains: Partial<Record<BackupDomain, unknown>> = {}; for (const [domain, key] of Object.entries(backupDomainKeys) as Array<[BackupDomain,string]>) { const raw = storage.getItem(key); if (raw === null) continue; try { const parsed = parseDomain(domain, raw); if (!secretLike(parsed)) domains[domain] = parsed; } catch { /* malformed domains are excluded instead of exported */ } } const envelope = { schemaVersion: 1 as const, appVersion: "1.4.0-beta.1", exportedAt: now(), domainVersions: Object.fromEntries((Object.keys(backupDomainKeys) as BackupDomain[]).map((domain) => [domain, 1])) as Record<BackupDomain,number>, domains }; return { ...envelope, checksum: checksumPayload(envelope) }; }
export function serializeWorkspaceBackup(backup: WorkspaceBackup): string { return JSON.stringify(backup, null, 2); }
export function containsSecretLikeKey(value: unknown): boolean { return secretLike(value); }

