/* eslint-disable react-refresh/only-export-components -- provider and hook are one public boundary. */
import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { useAgentLibrary } from "../agents/AgentLibraryContext";
import { useLanguage } from "../i18n/LanguageContext";
import { usePromptLibrary } from "../prompts/PromptLibraryContext";
import { clearSearchStorage } from "../search";
import { createCommandRegistry } from "./commandRegistry";
import { executeCommand } from "./commandExecutor";
import { loadCommandHistory, rememberCommand, saveCommandHistory } from "./commandHistory";
import { searchCommands } from "./commandSearch";
import type { WorkspaceCommand } from "./types";
import { createWorkspaceBackup, serializeWorkspaceBackup } from "../backup";

interface Value { openPalette: () => void; openShortcutHelp: () => void; closeOverlays: () => void }
const Context = createContext<Value | null>(null);
const copy = {
  he: { title: "לוח פקודות", search: "חיפוש פקודות", placeholder: "ניווט, יצירה או פעולה", empty: "לא נמצאו פקודות.", close: "סגירה", disabled: "לא זמין", confirmTitle: "אישור פעולה", confirm: "אישור והמשך", cancel: "ביטול", shortcuts: "קיצורי מקלדת", shortcutIntro: "הקיצורים פעילים כאשר המיקוד אינו בשדה עריכה." },
  en: { title: "Command Palette", search: "Search commands", placeholder: "Navigate, create, or act", empty: "No commands found.", close: "Close", disabled: "Unavailable", confirmTitle: "Confirm action", confirm: "Confirm and continue", cancel: "Cancel", shortcuts: "Keyboard shortcuts", shortcutIntro: "Shortcuts are active when focus is outside an editor." },
} as const;
const shortcutRows = [
  ["Ctrl/Cmd + K", "Command Palette", "לוח פקודות"], ["Ctrl/Cmd + Shift + P", "Command Palette", "לוח פקודות"],
  ["Ctrl/Cmd + Shift + F", "Global Search", "חיפוש גלובלי"], ["Ctrl/Cmd + Enter", "Run current Playground", "הרצת מגרש העבודה"],
  ["Ctrl/Cmd + S", "Save current editor", "שמירת העורך הנוכחי"], ["Escape", "Close active overlay", "סגירת שכבה פעילה"], ["?", "Shortcut help", "עזרה לקיצורים"],
] as const;
function editable(target: EventTarget | null) { return target instanceof HTMLElement && (target.isContentEditable || ["INPUT", "TEXTAREA", "SELECT"].includes(target.tagName)); }

export function CommandPaletteProvider({ children }: { children: ReactNode }) {
  const { language, setLanguage } = useLanguage(); const location = useLocation(); const navigate = useNavigate();
  const prompts = usePromptLibrary(); const agents = useAgentLibrary();
  const [open, setOpen] = useState(false); const [shortcutsOpen, setShortcutsOpen] = useState(false); const [query, setQuery] = useState("");
  const [active, setActive] = useState(0); const [pending, setPending] = useState<WorkspaceCommand>(); const [message, setMessage] = useState("");
  const [history, setHistory] = useState(loadCommandHistory); const dialogRef = useRef<HTMLDivElement>(null); const inputRef = useRef<HTMLInputElement>(null); const restoreRef = useRef<HTMLElement | null>(null);
  const parts = location.pathname.split("/").filter(Boolean); const currentEntity = parts[0] === "prompts" && parts.length === 2 ? "prompt" : parts[0] === "agents" && parts.length === 2 ? "agent" : "other";
  const commands = useMemo(() => createCommandRegistry({ route: location.pathname, currentEntity, backupAvailable: true }), [currentEntity, location.pathname]);
  const filtered = useMemo(() => searchCommands(commands, query, language, history.commandIds), [commands, history.commandIds, language, query]); const ui = copy[language];
  const openPalette = useCallback(() => { restoreRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setShortcutsOpen(false); setPending(undefined); setMessage(""); setQuery(""); setActive(0); setOpen(true); }, []);
  const openShortcutHelp = useCallback(() => { restoreRef.current = document.activeElement instanceof HTMLElement ? document.activeElement : null; setOpen(false); setShortcutsOpen(true); }, []);
  const closeOverlays = useCallback(() => { setOpen(false); setShortcutsOpen(false); setPending(undefined); requestAnimationFrame(() => restoreRef.current?.focus()); }, []);
  useEffect(() => { if (!open && !shortcutsOpen) return; const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; requestAnimationFrame(() => open ? inputRef.current?.focus() : dialogRef.current?.querySelector<HTMLElement>("button")?.focus()); const onKey = (event: globalThis.KeyboardEvent) => { if (event.key === "Escape") { event.preventDefault(); closeOverlays(); } if (event.key === "Tab") { const controls = dialogRef.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),a[href]'); if (!controls?.length) return; const first = controls[0], last = controls[controls.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }; document.addEventListener("keydown", onKey); return () => { document.body.style.overflow = previous; document.removeEventListener("keydown", onKey); }; }, [closeOverlays, open, shortcutsOpen]);
  useEffect(() => { const listener = (event: globalThis.KeyboardEvent) => { const modifier = event.ctrlKey || event.metaKey; if (modifier && ((event.key.toLowerCase() === "k") || (event.shiftKey && event.key.toLowerCase() === "p"))) { event.preventDefault(); openPalette(); return; } if (modifier && event.shiftKey && event.key.toLowerCase() === "f") { event.preventDefault(); navigate("/search"); return; } if (event.key === "?" && !modifier && !editable(event.target)) { event.preventDefault(); openShortcutHelp(); return; } if (modifier && event.key.toLowerCase() === "s" && (/^\/(prompts|agents)\/(new|[^/]+\/edit)/.test(location.pathname))) { event.preventDefault(); window.dispatchEvent(new CustomEvent("academy:save-current")); } if (modifier && event.key === "Enter" && location.pathname.startsWith("/playground/")) { event.preventDefault(); window.dispatchEvent(new CustomEvent("academy:run-current")); } }; window.addEventListener("keydown", listener); return () => window.removeEventListener("keydown", listener); }, [location.pathname, navigate, openPalette, openShortcutHelp]);
  const run = async (command: WorkspaceCommand, confirmed = false) => { if (!command.enabled) { setMessage(command.disabledReason?.[language] ?? ui.disabled); return; } if (command.confirmationRequired && !confirmed) { setPending(command); return; } const id = parts[1]; const result = await executeCommand(command, { navigate, language, setLanguage, toggleMotion: () => { const next = document.documentElement.dataset.motion === "reduced" ? "full" : "reduced"; document.documentElement.dataset.motion = next; try { localStorage.setItem("shabis-ai-academy:motion", next); } catch { /* optional */ } }, clearRecents: () => { clearSearchStorage(); }, showShortcuts: openShortcutHelp, copyRoute: async () => { if (!navigator.clipboard) throw new Error("Clipboard unavailable"); await navigator.clipboard.writeText(`${location.pathname}${location.search}${location.hash}`); }, favoriteCurrent: () => { if (currentEntity === "prompt" && id && prompts.get(id)) { prompts.favorite(id); return true; } if (currentEntity === "agent" && id && agents.get(id)) { agents.favorite(id); return true; } return false; }, exportWorkspace: () => { const backup = createWorkspaceBackup(); const url = URL.createObjectURL(new Blob([serializeWorkspaceBackup(backup)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = "shabis-ai-academy-workspace.json"; link.click(); URL.revokeObjectURL(url); return true; } }); setMessage(result.message); if (result.ok) { const next = rememberCommand(history, command.id); setHistory(next); saveCommandHistory(next); if (command.action.type !== "showShortcuts") closeOverlays(); } };
  return <Context.Provider value={{ openPalette, openShortcutHelp, closeOverlays }}>{children}
    {open && <div className="modal-layer command-layer" role="presentation"><div ref={dialogRef} className="command-dialog" role="dialog" aria-modal="true" aria-labelledby="command-title"><header><h2 id="command-title">{ui.title}</h2><button type="button" onClick={closeOverlays} aria-label={ui.close}>×</button></header>{pending ? <section className="command-confirm"><h3>{ui.confirmTitle}</h3><p>{pending.title[language]}</p><p>{pending.description[language]}</p><div><button type="button" onClick={() => setPending(undefined)}>{ui.cancel}</button><button type="button" onClick={() => void run(pending, true)}>{ui.confirm}</button></div></section> : <><label className="command-search">{ui.search}<input ref={inputRef} value={query} placeholder={ui.placeholder} onChange={(event) => { setQuery(event.target.value); setActive(0); }} onKeyDown={(event) => { if (event.key === "ArrowDown") { event.preventDefault(); setActive((value) => Math.min(filtered.length - 1, value + 1)); } if (event.key === "ArrowUp") { event.preventDefault(); setActive((value) => Math.max(0, value - 1)); } if (event.key === "Enter" && filtered[active]) { event.preventDefault(); void run(filtered[active]); } }} /></label><ul className="command-list">{filtered.map((command, index) => <li key={command.id}><button type="button" className={index === active ? "active" : ""} aria-disabled={!command.enabled} onMouseEnter={() => setActive(index)} onClick={() => void run(command)}><span><strong>{command.title[language]}</strong><small>{command.description[language]}</small></span><kbd>{command.category}</kbd>{!command.enabled && <em>{command.disabledReason?.[language] ?? ui.disabled}</em>}</button></li>)}</ul>{!filtered.length && <p>{ui.empty}</p>}</>}{message && <p role="status">{message}</p>}</div></div>}
    {shortcutsOpen && <div className="modal-layer command-layer" role="presentation"><div ref={dialogRef} className="command-dialog shortcut-dialog" role="dialog" aria-modal="true" aria-labelledby="shortcuts-title"><header><h2 id="shortcuts-title">{ui.shortcuts}</h2><button type="button" onClick={closeOverlays} aria-label={ui.close}>×</button></header><p>{ui.shortcutIntro}</p><dl>{shortcutRows.map(([keys, en, he]) => <div key={keys}><dt><kbd>{keys}</kbd></dt><dd>{language === "he" ? he : en}</dd></div>)}</dl></div></div>}
  </Context.Provider>;
}
export function useCommandPalette() { const value = useContext(Context); if (!value) throw new Error("Missing CommandPaletteProvider"); return value; }
