import { useState } from "react";
import { Link } from "react-router-dom";
import { useAgentLibrary } from "../agents/AgentLibraryContext";
import { starterAgents } from "../agents/catalog";
import { useLanguage } from "../i18n/LanguageContext";
import { useRuntime } from "../runtime/RuntimeContext";
import type { MockScenario, RuntimeHistoryRecord } from "../runtime";

export function AgentPlaygroundPage() {
  const { language } = useLanguage(); const { state, importFromCatalog } = useAgentLibrary(); const runtime = useRuntime();
  const [source, setSource] = useState(`starter:${starterAgents[0].id}`); const [input, setInput] = useState("Review the supplied local sample."); const [scenario, setScenario] = useState<MockScenario>("success"); const [mode, setMode] = useState<"mock" | "dryRun" | "liveReserved">("mock"); const [record, setRecord] = useState<RuntimeHistoryRecord>();
  const starter = source.startsWith("starter:") ? starterAgents.find((agent) => `starter:${agent.id}` === source) : undefined; const mine = state.agents.find((agent) => `mine:${agent.id}` === source);
  const name = starter?.name[language] ?? mine?.name ?? "Agent"; const tools = starter?.plannedTools ?? mine?.tools ?? ["none"];
  const text = language === "he" ? { title: "מגרש משחקים לסוכנים", select: "בחירת סוכן", input: "קלט לדוגמה", scenario: "תרחיש", run: "הרצה", import: "ייבוא הסוכן", live: "הרצה חיה מושבתת", planned: "כלים מתוכננים — אינם מחוברים", output: "פלט וציר זמן", history: "היסטוריית הרצות", saveProject: "שמירה לפרויקט תתאפשר לאחר בחירת פרויקט" } : { title: "Agent Playground", select: "Select agent", input: "Sample input", scenario: "Scenario", run: "Run", import: "Import agent", live: "Live execution is disabled", planned: "Planned tools — not connected", output: "Output and timeline", history: "Run History", saveProject: "Save to project becomes available after selecting a project" };
  const execute = async () => { if (mode === "liveReserved") return; const payload = { text: `${name}\n${input}`, scenario, plannedToolIds: ["none"] }; setRecord(mode === "mock" ? await runtime.startRequest(payload) : runtime.previewRequest(payload)); };
  return <div className="page playground-page"><header className="page-header"><div><h1>{text.title}</h1><p>{text.planned}</p></div><Link to="/runs">{text.history}</Link></header><div className="playground-grid"><section className="glass-panel"><label>{text.select}<select value={source} onChange={(event) => setSource(event.target.value)}><optgroup label="Starter Agents">{starterAgents.map((agent) => <option key={agent.id} value={`starter:${agent.id}`}>{agent.name[language]}</option>)}</optgroup><optgroup label="My Agents">{state.agents.map((agent) => <option key={agent.id} value={`mine:${agent.id}`}>{agent.name}</option>)}</optgroup></select></label><label>{text.input}<textarea value={input} onChange={(event) => setInput(event.target.value)} /></label><label>{text.scenario}<select value={scenario} onChange={(event) => setScenario(event.target.value as MockScenario)}>{["success", "retryThenSuccess", "retryExhausted", "approvalRequired", "cancelled"].map((value) => <option key={value}>{value}</option>)}</select></label><label>Mode<select value={mode} onChange={(event) => setMode(event.target.value as typeof mode)}><option value="mock">Mock</option><option value="dryRun">Dry Run</option><option value="liveReserved" disabled>Live</option></select></label><p>{mode === "liveReserved" && text.live}</p><h2>{text.planned}</h2><ul>{tools.map((tool) => <li key={tool}>{tool}</li>)}</ul><div className="card-actions"><button disabled={mode === "liveReserved"} onClick={execute}>{text.run}</button>{starter && <button onClick={() => importFromCatalog(starter, language)}>{text.import}</button>}<button disabled title={text.saveProject}>{text.saveProject}</button></div></section><aside className="glass-panel"><h2>{text.output}</h2>{record ? <><p>{record.result.status}</p><pre className="runtime-output">{record.result.output ?? record.result.dryRunPreview?.assembledPrompt}</pre><ol>{record.result.events.map((event) => <li key={event.id}>{event.sequence}. {event.safeSummary}</li>)}</ol></> : <p>{mode === "liveReserved" ? text.live : text.planned}</p>}</aside></div></div>;
}
