import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { useLanguage } from "../i18n/LanguageContext";
import { usePromptLibrary } from "../prompts/PromptLibraryContext";
import { emptyInput } from "../prompts/types";
import { assemblePrompt, estimateTokens, loadWorkspace, PROMPT_PLAYGROUND_KEY, saveBoundedWorkspace, type PromptWorkspaceInput } from "../playgrounds";
import { useRuntime } from "../runtime/RuntimeContext";
import type { RuntimeHistoryRecord } from "../runtime";

const initial: PromptWorkspaceInput = { systemInstruction: "Act as a careful educational assistant.", userPrompt: "Review {{input}} and identify risks.", variables: { input: "sample requirement" }, context: "Use only supplied information.", constraints: "Do not invent facts or execute tools.", outputFormat: "Prioritized findings with verification steps.", examples: "" };

export function PromptPlaygroundPage() {
  const { language } = useLanguage(); const { create } = usePromptLibrary(); const runtime = useRuntime();
  const [workspace, setWorkspace] = useState(() => loadWorkspace(PROMPT_PLAYGROUND_KEY, initial));
  const [mode, setMode] = useState<"mock" | "dryRun" | "liveReserved">("mock"); const [record, setRecord] = useState<RuntimeHistoryRecord>(); const [dirty, setDirty] = useState(false);
  const assembled = useMemo(() => assemblePrompt(workspace), [workspace]);
  useEffect(() => { const prevent = (event: BeforeUnloadEvent) => { if (dirty) event.preventDefault(); }; addEventListener("beforeunload", prevent); return () => removeEventListener("beforeunload", prevent); }, [dirty]);
  const text = language === "he" ? { title: "מגרש משחקים לפרומפטים", simulated: "פלט Mock מדומה", preview: "תצוגה מקדימה בלבד", live: "הרצה חיה מושבתת", run: "הרצה", save: "שמירת סביבת עבודה", savePrompt: "שמירה לפרומפטים שלי", assembled: "פרומפט מורכב", provider: "מצב ספק", history: "היסטוריית הרצות", tokens: "הערכת טוקנים", variables: "משתנים (JSON)" } : { title: "Prompt Playground", simulated: "Simulated Mock output", preview: "Preview only", live: "Live execution is disabled", run: "Run", save: "Save workspace", savePrompt: "Save to My Prompts", assembled: "Assembled prompt", provider: "Provider status", history: "Run History", tokens: "Approximate tokens", variables: "Variables (JSON)" };
  const patch = (value: Partial<PromptWorkspaceInput>) => { setWorkspace((current) => ({ ...current, ...value })); setDirty(true); };
  const execute = async () => { if (mode === "liveReserved") return; const input = { text: assembled, systemInstruction: workspace.systemInstruction, variables: workspace.variables, plannedToolIds: ["none"] }; setRecord(mode === "mock" ? await runtime.startRequest(input) : runtime.previewRequest(input)); };
  return <div className="page playground-page"><header className="page-header"><div><h1>{text.title}</h1><p>{mode === "mock" ? text.simulated : mode === "dryRun" ? text.preview : text.live}</p></div><Link to="/runs">{text.history}</Link></header><div className="playground-grid"><section className="glass-panel"><label>System instruction<textarea value={workspace.systemInstruction} onChange={(event) => patch({ systemInstruction: event.target.value })} /></label><label>User prompt<textarea value={workspace.userPrompt} onChange={(event) => patch({ userPrompt: event.target.value })} /></label><label>{text.variables}<textarea value={JSON.stringify(workspace.variables, null, 2)} onChange={(event) => { try { patch({ variables: JSON.parse(event.target.value) as Record<string, string> }); } catch { /* retain last valid variables */ } }} /></label>{(["context", "constraints", "outputFormat", "examples"] as const).map((field) => <label key={field}>{field}<textarea value={workspace[field]} onChange={(event) => patch({ [field]: event.target.value })} /></label>)}<label>Mode<select value={mode} onChange={(event) => setMode(event.target.value as typeof mode)}><option value="mock">Mock</option><option value="dryRun">Dry Run</option><option value="liveReserved" disabled>Live — disabled</option></select></label><div className="card-actions"><button disabled={mode === "liveReserved"} onClick={execute}>{text.run}</button><button onClick={() => { saveBoundedWorkspace(PROMPT_PLAYGROUND_KEY, workspace); setDirty(false); }}>{text.save}</button><button onClick={() => create({ ...emptyInput, title: language === "he" ? "פרומפט ממגרש המשחקים" : "Playground Prompt", description: text.preview, language, task: workspace.userPrompt, role: workspace.systemInstruction, context: workspace.context, constraints: workspace.constraints, outputFormat: workspace.outputFormat, examples: workspace.examples })}>{text.savePrompt}</button></div></section><aside className="glass-panel"><h2>{text.assembled}</h2><p>{text.tokens}: {estimateTokens(assembled)}</p><pre className="runtime-output">{assembled}</pre><h2>{text.provider}</h2><p>{mode === "liveReserved" ? text.live : mode === "mock" ? "Mock — available" : "Dry Run — local"}</p>{record && <><h2>{record.result.dryRunPreview ? text.preview : text.simulated}</h2><pre className="runtime-output">{record.result.dryRunPreview?.assembledPrompt ?? record.result.output}</pre></>}</aside></div></div>;
}
