import { useMemo, useState, type KeyboardEvent } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { starterAgents } from "../agents/catalog";
import { useAgentLibrary } from "../agents/AgentLibraryContext";
import { courseLessons, courseModules } from "../course/courseData";
import { helpSections } from "../help/helpData";
import { useLanguage } from "../i18n/LanguageContext";
import { useKnowledge } from "../knowledge";
import { userDocs } from "../platform/docsIndex";
import { roadmapItems } from "../platform/roadmap";
import { useProjects } from "../projects";
import { starterCatalog } from "../prompts/catalog";
import { usePromptLibrary } from "../prompts/PromptLibraryContext";
import { packedPrompts, promptPacks } from "../prompts/packs";
import { useRuntime } from "../runtime/RuntimeContext";
import { createSafeHighlight, createSearchIndex, groupSearchResults, loadSearchStorage, rememberSearch, rememberSearchResult, saveSearchStorage, searchDocuments, type SearchDocument, type SearchEntityType, type SearchFilters } from "../search";

const typeOrder: SearchEntityType[] = ["lesson", "module", "prompt", "promptPack", "agent", "project", "document", "run", "help", "documentation", "roadmap", "changelog"];
const labels = {
  he: { title: "חיפוש בכל סביבת העבודה", description: "חיפוש מקומי ודטרמיניסטי. שום תוכן לא נשלח לרשת.", query: "מה לחפש?", placeholder: "שיעור, פרומפט, סוכן, פרויקט או מסמך", filters: "מסננים", entity: "סוג פריט", category: "קטגוריה", language: "שפה", availability: "זמינות", all: "הכול", hebrew: "עברית", english: "אנגלית", mixed: "מעורבת", favorites: "מועדפים בלבד", recent: "בשימוש לאחרונה", results: "תוצאות", empty: "לא נמצאו תוצאות מתאימות.", recentEmpty: "פריטים שנפתחו לאחרונה יופיעו כאן.", available: "זמין", planned: "מתוכנן", disabled: "מושבת", source: "מקור" },
  en: { title: "Search the entire workspace", description: "Local, deterministic search. No content is sent to the network.", query: "What are you looking for?", placeholder: "Lesson, prompt, agent, project, or document", filters: "Filters", entity: "Entity type", category: "Category", language: "Language", availability: "Availability", all: "All", hebrew: "Hebrew", english: "English", mixed: "Mixed", favorites: "Favorites only", recent: "Recently used", results: "results", empty: "No matching results.", recentEmpty: "Recently opened items will appear here.", available: "Available", planned: "Planned", disabled: "Disabled", source: "Source" },
} as const;
const typeLabels: Record<"he" | "en", Record<SearchEntityType, string>> = {
  he: { lesson: "שיעורים", module: "מודולים", prompt: "פרומפטים", promptPack: "חבילות פרומפטים", agent: "סוכנים", project: "פרויקטים", document: "מסמכי ידע", run: "הרצות", help: "מדריכי עזרה", documentation: "תיעוד", roadmap: "מפת דרכים", changelog: "יומן שינויים" },
  en: { lesson: "Lessons", module: "Modules", prompt: "Prompts", promptPack: "Prompt packs", agent: "Agents", project: "Projects", document: "Knowledge documents", run: "Runs", help: "Help", documentation: "Documentation", roadmap: "Roadmap", changelog: "Changelog" },
};

function Highlight({ value, query }: { value: string; query: string }) { return <>{createSafeHighlight(value, query).map((segment, index) => segment.matched ? <mark key={`${segment.text}-${index}`}>{segment.text}</mark> : <span key={`${segment.text}-${index}`}>{segment.text}</span>)}</>; }

export function SearchPage() {
  const { language } = useLanguage(); const copy = labels[language];
  const [params, setParams] = useSearchParams(); const [query, setQuery] = useState(params.get("q") ?? "");
  const [filters, setFilters] = useState<Partial<SearchFilters>>({ entityTypes: [], category: "all", language: "all", favoritesOnly: false, recentOnly: false, availability: "all" });
  const [storageState, setStorageState] = useState(loadSearchStorage); const [activeIndex, setActiveIndex] = useState(0); const navigate = useNavigate();
  const { state: prompts } = usePromptLibrary(); const { state: agents } = useAgentLibrary(); const { state: projects } = useProjects(); const { state: knowledge } = useKnowledge(); const { runs } = useRuntime();
  const documents = useMemo(() => createSearchIndex([
    courseModules.map((module) => ({ id: `module:${module.id}`, entityType: "module", title: module.title, description: module.description, keywords: module.lessonIds, tags: [], route: "/lessons", availability: "available", updatedAt: "2026-07-13T00:00:00.000Z", source: "builtIn" } satisfies SearchDocument)),
    courseLessons.map((lesson) => ({ id: `lesson:${lesson.id}`, entityType: "lesson", title: lesson.title, description: lesson.summary, keywords: lesson.learningObjectives.flatMap((item) => [item.he, item.en]), tags: [lesson.difficulty, lesson.moduleId], route: `/lessons/${lesson.slug}`, availability: lesson.available ? "available" : "planned", updatedAt: "2026-07-13T00:00:00.000Z", source: "builtIn", category: lesson.moduleId } satisfies SearchDocument)),
    prompts.prompts.map((prompt) => ({ id: `prompt:${prompt.id}`, entityType: "prompt", title: { he: prompt.title, en: prompt.title }, description: { he: prompt.description, en: prompt.description }, keywords: [prompt.role, prompt.task, prompt.context], tags: prompt.tags, route: `/prompts/${prompt.id}`, availability: "available", updatedAt: prompt.updatedAt, source: "user", category: prompt.category, language: prompt.language, favorite: prompt.isFavorite } satisfies SearchDocument)),
    starterCatalog.map((prompt) => ({ id: `catalog-prompt:${prompt.id}`, entityType: "prompt", title: { he: prompt.title, en: prompt.title }, description: { he: prompt.description, en: prompt.description }, keywords: [prompt.prompt], tags: prompt.tags, route: `/prompts/catalog/${prompt.id}`, availability: "available", updatedAt: prompt.sourceImportedAt, source: "builtIn", category: prompt.category, language: prompt.language === "unknown" ? "mixed" : prompt.language } satisfies SearchDocument)),
    packedPrompts.map((prompt) => ({ id: `packed-prompt:${prompt.id}`, entityType: "prompt", title: prompt.title, description: prompt.description, keywords: [prompt.task.he, prompt.task.en], tags: prompt.tags, route: `/prompts/packs?prompt=${prompt.id}`, availability: "available", updatedAt: "2026-07-13T00:00:00.000Z", source: "builtIn", category: prompt.category, language: prompt.contentLanguage } satisfies SearchDocument)),
    promptPacks.map((pack) => ({ id: `pack:${pack.id}`, entityType: "promptPack", title: pack.title, description: pack.description, keywords: [], tags: [pack.category], route: `/prompts/packs?pack=${pack.id}`, availability: "available", updatedAt: "2026-07-13T00:00:00.000Z", source: "builtIn", category: pack.category } satisfies SearchDocument)),
    agents.agents.map((agent) => ({ id: `agent:${agent.id}`, entityType: "agent", title: { he: agent.name, en: agent.name }, description: { he: agent.description, en: agent.description }, keywords: [agent.goal, agent.role, agent.instructions], tags: agent.tags, route: `/agents/${agent.id}`, availability: "available", updatedAt: agent.updatedAt, source: "user", category: agent.category, language: agent.language, favorite: agent.isFavorite } satisfies SearchDocument)),
    starterAgents.map((agent) => ({ id: `starter-agent:${agent.id}`, entityType: "agent", title: agent.name, description: agent.description, keywords: [agent.goal.he, agent.goal.en, agent.role.he, agent.role.en], tags: [agent.category], route: `/agents/catalog?agent=${agent.id}`, availability: "available", updatedAt: "2026-07-13T00:00:00.000Z", source: "builtIn", category: agent.category } satisfies SearchDocument)),
    projects.projects.map((project) => ({ id: `project:${project.id}`, entityType: "project", title: { he: project.name, en: project.name }, description: { he: project.description, en: project.description }, keywords: [project.notes], tags: project.tags, route: `/projects/${project.id}`, availability: "available", updatedAt: project.updatedAt, source: "user", category: project.category, favorite: project.favorite } satisfies SearchDocument)),
    knowledge.documents.map((document) => ({ id: `document:${document.id}`, entityType: "document", title: { he: document.title, en: document.title }, description: { he: document.description, en: document.description }, keywords: [], tags: document.tags, route: `/knowledge/${document.id}`, availability: "available", updatedAt: document.updatedAt, source: "user", category: document.contentType } satisfies SearchDocument)),
    runs.map((run) => ({ id: `run:${run.id}`, entityType: "run", title: { he: `הרצת ${run.request.mode}`, en: `${run.request.mode} run` }, description: { he: run.result.events.at(-1)?.safeSummary ?? "", en: run.result.events.at(-1)?.safeSummary ?? "" }, keywords: [run.result.status, run.request.scenario], tags: [run.request.mode], route: `/runs/${run.id}`, availability: "available", updatedAt: run.updatedAt, source: "workspace" } satisfies SearchDocument)),
    helpSections.map((help) => ({ id: `help:${help.id}`, entityType: "help", title: { he: help.titleHe, en: help.titleEn }, description: { he: help.summaryHe, en: help.summaryEn }, keywords: help.keywords, tags: [help.category], route: `/how-to#${help.slug}`, availability: "available", updatedAt: "2026-07-13T00:00:00.000Z", source: "builtIn", category: help.category } satisfies SearchDocument)),
    userDocs.map(([id, en, he, description]) => ({ id: `docs:${id}`, entityType: "documentation", title: { he, en }, description: { he: description, en: description }, keywords: [], tags: [], route: `/docs?doc=${id}`, availability: "available", updatedAt: "2026-07-13T00:00:00.000Z", source: "builtIn" } satisfies SearchDocument)),
    roadmapItems.map((item, index) => ({ id: `roadmap:${index}:${item.version}`, entityType: "roadmap", title: item.title, description: item.summary, keywords: [item.version], tags: [item.status], route: "/roadmap", availability: item.status === "planned" ? "planned" : "available", updatedAt: "2026-07-13T00:00:00.000Z", source: "builtIn" } satisfies SearchDocument)),
    [{ id: "changelog:1.2", entityType: "changelog", title: { he: "יומן שינויים", en: "Changelog" }, description: { he: "גרסאות ושינויים באקדמיה", en: "Academy releases and changes" }, keywords: ["1.2.0-beta.1", "1.1.0-beta.1", "release", "radar"], tags: [], route: "/changelog", availability: "available", updatedAt: "2026-07-13T00:00:00.000Z", source: "builtIn" } satisfies SearchDocument],
  ]), [agents.agents, knowledge.documents, projects.projects, prompts.prompts, runs]);
  const categories = useMemo(() => [...new Set(documents.map((document) => document.category).filter((category): category is string => Boolean(category)))].sort((left, right) => left.localeCompare(right, language)), [documents, language]);
  const results = useMemo(() => searchDocuments(documents, query, { language, filters, recentIds: storageState.recentIds }), [documents, filters, language, query, storageState.recentIds]);
  const groups = groupSearchResults(results); const flat = groups.flatMap((group) => group.results);
  const persistQuery = () => { const next = rememberSearch(storageState, query); setStorageState(next); saveSearchStorage(next); setParams(query ? { q: query } : {}); };
  const openResult = (id: string, route: string) => { const next = rememberSearchResult(rememberSearch(storageState, query), id); setStorageState(next); saveSearchStorage(next); navigate(route); };
  const onKeys = (event: KeyboardEvent<HTMLDivElement>) => { if (!flat.length) return; if (event.key === "ArrowDown") { event.preventDefault(); setActiveIndex((index) => Math.min(flat.length - 1, index + 1)); } if (event.key === "ArrowUp") { event.preventDefault(); setActiveIndex((index) => Math.max(0, index - 1)); } if (event.key === "Enter" && event.target instanceof HTMLInputElement) { event.preventDefault(); const result = flat[activeIndex]; if (result) openResult(result.id, result.route); } };
  return <div className="page search-page" onKeyDown={onKeys}>
    <header className="page-heading"><div><h1>{copy.title}</h1><p>{copy.description}</p></div><Link to="/how-to">{language === "he" ? "עזרה" : "Help"}</Link></header>
    <form className="search-toolbar" role="search" onSubmit={(event) => { event.preventDefault(); persistQuery(); }}>
      <label className="search-query">{copy.query}<input autoFocus value={query} placeholder={copy.placeholder} onChange={(event) => { setQuery(event.target.value); setActiveIndex(0); }} /></label>
      <fieldset><legend>{copy.filters}</legend><label>{copy.entity}<select value={filters.entityTypes?.[0] ?? "all"} onChange={(event) => setFilters((current) => ({ ...current, entityTypes: event.target.value === "all" ? [] : [event.target.value as SearchEntityType] }))}><option value="all">{copy.all}</option>{typeOrder.map((type) => <option key={type} value={type}>{typeLabels[language][type]}</option>)}</select></label><label>{copy.category}<select value={filters.category} onChange={(event) => setFilters((current) => ({ ...current, category: event.target.value }))}><option value="all">{copy.all}</option>{categories.map((category) => <option key={category} value={category}>{category}</option>)}</select></label><label>{copy.language}<select value={filters.language} onChange={(event) => setFilters((current) => ({ ...current, language: event.target.value as SearchFilters["language"] }))}><option value="all">{copy.all}</option><option value="he">{copy.hebrew}</option><option value="en">{copy.english}</option><option value="mixed">{copy.mixed}</option></select></label><label>{copy.availability}<select value={filters.availability} onChange={(event) => setFilters((current) => ({ ...current, availability: event.target.value as SearchFilters["availability"] }))}><option value="all">{copy.all}</option><option value="available">{copy.available}</option><option value="planned">{copy.planned}</option><option value="disabled">{copy.disabled}</option></select></label><label className="check-filter"><input type="checkbox" checked={filters.favoritesOnly} onChange={(event) => setFilters((current) => ({ ...current, favoritesOnly: event.target.checked }))} />{copy.favorites}</label><label className="check-filter"><input type="checkbox" checked={filters.recentOnly} onChange={(event) => setFilters((current) => ({ ...current, recentOnly: event.target.checked }))} />{copy.recent}</label></fieldset>
    </form>
    <p role="status" aria-live="polite">{results.length} {copy.results}</p>
    {!groups.length ? <div className="search-empty"><p>{query ? copy.empty : copy.recentEmpty}</p></div> : <div className="search-groups">{groups.map((group) => <section key={group.entityType}><h2>{typeLabels[language][group.entityType]} <span>{group.results.length}</span></h2><ul className="search-results">{group.results.map((result) => { const index = flat.findIndex((item) => item.id === result.id); return <li key={result.id} className={index === activeIndex ? "active" : ""}><button type="button" onMouseEnter={() => setActiveIndex(index)} onClick={() => openResult(result.id, result.route)}><strong><Highlight value={result.title[language]} query={query} /></strong><span><Highlight value={result.description[language]} query={query} /></span><small>{result.availability === "available" ? copy.available : copy.planned} · {copy.source}: {result.source}</small></button></li>; })}</ul></section>)}</div>}
  </div>;
}
