import { useState } from "react";
import { Link } from "react-router-dom";
import { applyWorkspaceImport, createWorkspaceBackup, previewWorkspaceImport, serializeWorkspaceBackup, type BackupDomain, type ImportStrategy, type WorkspaceImportPreview } from "../backup";
import { useAgentLibrary } from "../agents/AgentLibraryContext";
import { useCourseProgress } from "../course/CourseProgressContext";
import { useLanguage } from "../i18n/LanguageContext";
import { useKnowledge } from "../knowledge";
import { useProjects } from "../projects";
import { usePromptLibrary } from "../prompts/PromptLibraryContext";
import { useRuntime } from "../runtime/RuntimeContext";
import { useWorkflows } from "../workflows";
import { useWorkspace } from "../workspace";
import { useExperience } from "../experience";
export function SettingsPage() {
  const { language, setLanguage, t } = useLanguage(); const { resetProgress } = useCourseProgress(); const prompts = usePromptLibrary(); const agents = useAgentLibrary(); const runtime = useRuntime(); const projects = useProjects(); const knowledge = useKnowledge(); const workflows = useWorkflows(); const workspace = useWorkspace(); const experience = useExperience();
  const [message, setMessage] = useState(""); const [reducedMotion, setReducedMotion] = useState(() => localStorage.getItem("shabis-ai-academy.motion") === "reduced"); const [preview, setPreview] = useState<WorkspaceImportPreview>(); const [strategies, setStrategies] = useState<Partial<Record<BackupDomain,ImportStrategy>>>({});
  const exportWorkspace = () => { const backup = createWorkspaceBackup(); const url = URL.createObjectURL(new Blob([serializeWorkspaceBackup(backup)], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `shabis-ai-academy-workspace-${backup.exportedAt.slice(0,10)}.json`; anchor.click(); URL.revokeObjectURL(url); };
  return <div className="page settings-page"><div className="page-heading"><h1>{t("pages.settingsTitle")}</h1><p>{t("pages.settingsDescription")}</p><Link to="/how-to#settings">{language === "he" ? "עזרה" : "Help"}</Link></div>
    <section className="settings-card" aria-labelledby="language-settings-title"><h2 id="language-settings-title">{t("settings.languageTitle")}</h2><p>{t("settings.languageDescription")}</p><div className="language-options" role="radiogroup" aria-label={t("settings.languageTitle")}><button type="button" role="radio" aria-checked={language === "he"} onClick={() => setLanguage("he")}><span lang="he">{t("settings.hebrew")}</span>{language === "he" && <small>{t("settings.selected")}</small>}</button><button type="button" role="radio" aria-checked={language === "en"} onClick={() => setLanguage("en")}><span lang="en">{t("settings.english")}</span>{language === "en" && <small>{t("settings.selected")}</small>}</button></div></section>
    <section className="settings-card" aria-labelledby="experience-mode-title"><h2 id="experience-mode-title">{language === "he" ? "מצב חוויה" : "Experience mode"}</h2><p>{language === "he" ? "המצב משנה הסברים וחשיפה הדרגתית בלבד — לא הרשאות או נתונים." : "The mode changes guidance and progressive disclosure only — never permissions or data."}</p><div className="language-options" role="radiogroup" aria-label={language === "he" ? "מצב חוויה" : "Experience mode"}><button type="button" role="radio" aria-checked={experience.mode === "beginner"} onClick={() => experience.setMode("beginner")}><span>{language === "he" ? "מצב מתחיל" : "Beginner Mode"}</span>{experience.mode === "beginner" && <small>{t("settings.selected")}</small>}</button><button type="button" role="radio" aria-checked={experience.mode === "advanced"} onClick={() => experience.setMode("advanced")}><span>{language === "he" ? "מצב מתקדם" : "Advanced Mode"}</span>{experience.mode === "advanced" && <small>{t("settings.selected")}</small>}</button></div>{experience.mode === "advanced" && <label className="check-filter"><input type="checkbox" checked={experience.developerModeEnabled} onChange={(event) => experience.setDeveloperModeEnabled(event.target.checked)} />{language === "he" ? "הצגת מצב מפתחים" : "Show Developer Mode"}</label>}</section>
    <section className="settings-card"><h2>{language === "he" ? "תנועה ופרטיות" : "Motion and privacy"}</h2><label className="check-filter"><input type="checkbox" checked={reducedMotion} onChange={(event) => { setReducedMotion(event.target.checked); localStorage.setItem("shabis-ai-academy.motion", event.target.checked ? "reduced" : "full"); document.documentElement.dataset.motion = event.target.checked ? "reduced" : "full"; }} />{language === "he" ? "הפחתת תנועה" : "Reduce motion"}</label><p>{language === "he" ? "הנתונים נשמרים בדפדפן. אין להזין מידע סודי או רגיש." : "Data stays in this browser. Do not enter confidential or sensitive information."}</p></section>
    <section className="settings-card"><h2>{language === "he" ? "איפוס לפי תחום" : "Domain resets"}</h2><p>{language === "he" ? "כל פעולה משפיעה רק על התחום המסומן." : "Each action affects only the named domain."}</p><div className="card-actions"><button onClick={() => prompts.clear()}>My Prompts</button><button onClick={() => agents.clear()}>My Agents</button><button onClick={() => runtime.clearHistory()}>Run History</button><button onClick={() => projects.clear()}>Projects</button><button onClick={() => knowledge.clear()}>Knowledge Base</button><button onClick={() => workflows.clear()}>Workflows</button><button onClick={() => workspace.reset("notifications")}>Notifications</button><button onClick={() => workspace.reset("analytics")}>Analytics</button></div></section>
    <section className="settings-card backup-settings"><h2>{language === "he" ? "גיבוי מלא של סביבת העבודה" : "Complete Workspace backup"}</h2><p>{language === "he" ? "הקובץ כולל נתונים שכתבת. הוא אינו כולל מפתחות API או סודות. בדוק אותו לפני שיתוף." : "The file contains user-authored data. It excludes API keys and secrets. Review it before sharing."}</p><button type="button" onClick={exportWorkspace}>{language === "he" ? "ייצוא גיבוי JSON" : "Export JSON backup"}</button><label>{language === "he" ? "בחירת קובץ לייבוא" : "Choose import file"}<input type="file" accept="application/json,.json" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; const next = previewWorkspaceImport(await file.text()); setPreview(next); setStrategies(Object.fromEntries(next.domains.map((domain) => [domain.domain, "merge"]))); setMessage(next.valid ? (language === "he" ? "התצוגה המקדימה מוכנה. עדיין לא נכתב מידע." : "Preview ready. No data has been written.") : (language === "he" ? "קובץ הייבוא אינו תקין." : "Import file is invalid.")); }} /></label>{preview && <div className="backup-preview"><h3>{language === "he" ? "תצוגה מקדימה ועימותים" : "Preview and conflicts"}</h3>{preview.errors.length > 0 && <div role="alert"><ul>{preview.errors.map((error) => <li key={error}>{error}</li>)}</ul></div>}<table><thead><tr><th>{language === "he" ? "תחום" : "Domain"}</th><th>{language === "he" ? "נכנס" : "Incoming"}</th><th>{language === "he" ? "קיים" : "Existing"}</th><th>{language === "he" ? "עימותים" : "Conflicts"}</th><th>{language === "he" ? "אסטרטגיה" : "Strategy"}</th></tr></thead><tbody>{preview.domains.map((domain) => <tr key={domain.domain}><td>{domain.domain}</td><td>{domain.incomingCount}</td><td>{domain.existingCount}</td><td>{domain.conflicts}</td><td><select value={strategies[domain.domain] ?? "merge"} onChange={(event) => setStrategies((value) => ({ ...value, [domain.domain]: event.target.value as ImportStrategy }))}><option value="merge">Merge</option><option value="replace">Replace</option><option value="skip">Skip</option></select></td></tr>)}</tbody></table><button type="button" disabled={!preview.valid} onClick={() => { const report = applyWorkspaceImport(preview, strategies); setMessage(report.ok ? (language === "he" ? "הייבוא הושלם. סביבת העבודה תיטען מחדש." : "Import completed. The workspace will reload.") : report.rolledBack ? (language === "he" ? "הייבוא נכשל וכל השינויים בוטלו." : "Import failed and all changes were rolled back.") : (language === "he" ? "הייבוא נכשל." : "Import failed.")); if (report.ok) window.setTimeout(() => location.reload(), 100); }}>{language === "he" ? "אישור וייבוא" : "Confirm import"}</button></div>}<Link to="/developer">{language === "he" ? "פתיחת מצב מפתחים" : "Open Developer Mode"}</Link></section>
    <section className="settings-card" aria-labelledby="progress-settings-title"><h2 id="progress-settings-title">{t("settings.progressTitle")}</h2><p>{t("settings.progressDescription")}</p><button className="danger-button" type="button" onClick={() => { if (window.confirm(t("settings.resetConfirm"))) { resetProgress(); setMessage(t("settings.resetSuccess")); } }}>{t("settings.resetProgress")}</button>{message && <p role="status">{message}</p>}</section>
  </div>;
}
