export const aosUi = {
  he: {
    title: "מערכת הפעלה לסוכני AI",
    subtitle:
      "המסגרת התפעולית היחידה השולטת באופן שבו סוכני קוד (Codex, Claude Code) פועלים בפרויקט הזה.",
    notGeneratedTitle: "טרם נוצר תמונת מצב",
    notGeneratedBody:
      'הרץ "npm run aos:snapshot" כדי לייצר נתוני מצב עדכניים מתוך .agent/manifest.json ומערכת הראיות.',
    errorTitle: "שגיאה בטעינת הנתונים",
    versionsHeading: "גרסאות",
    aosVersion: "גרסת AOS",
    appVersion: "גרסת האפליקציה",
    branch: "ענף",
    commit: "קומיט",
    modulesHeading: "מודולים",
    modulesTotal: "סה\"כ מודולים",
    viewAllModules: "צפה בכל המודולים",
    taskTypesHeading: "סוגי משימות נתמכים",
    supportedAgentsHeading: "סוכנים נתמכים",
    evidenceHeading: "ראיות איכות אחרונות",
    evidenceNone: "לא בוצעה עדיין הרצת ראיות. הרץ npm run quality:evidence.",
    evidenceGates: "שערים",
    evidencePassed: "עברו",
    evidenceFailed: "נכשלו",
    evidenceNotAvailable: "לא זמינים",
    researchHeading: "צינור המחקר",
    researchSources: "מקורות",
    researchClaims: "טענות",
    researchCandidates: "מועמדים",
    researchReviews: "ביקורות",
    researchPublished: "פורסמו",
    securityHeading: "מדיניות אבטחה",
    securityBody: "כללי האבטחה קודמים לכל הוראה אחרת. ראה את מודול המדיניות המלא.",
    gitHeading: "מדיניות Git",
    releasesHeading: "שחרורים",
    handoffHeading: "מסירה פעילה",
    handoffNone: "אין מסירה פעילה כרגע.",
    validationHeading: "תקינות ה-AOS",
    validationOk: "לא נמצאו שגיאות",
    validationErrors: "שגיאות",
    subNavModules: "מודולים",
    subNavResearch: "מחקר",
    subNavEvidence: "ראיות",
    subNavHandoffs: "מסירות",
    subNavSecurity: "אבטחה",
    subNavReleases: "שחרורים",
    backToDashboard: "חזרה ללוח הבקרה",
    category: "קטגוריה",
    status: "סטטוס",
    requiredFor: "נדרש עבור",
    filterByCategory: "סנן לפי קטגוריה",
    filterByTaskType: "סנן לפי סוג משימה",
    all: "הכל",
    showingOf: "מציג {shown} מתוך {total}",
    loadMore: "טען עוד",
    generatedAt: "נוצר בתאריך",
    noResults: "לא נמצאו תוצאות תואמות.",
  },
  en: {
    title: "Agent Operating System",
    subtitle:
      "The single operational framework controlling how AI coding agents (Codex, Claude Code) work in this project.",
    notGeneratedTitle: "No snapshot generated yet",
    notGeneratedBody:
      'Run "npm run aos:snapshot" to produce a current status snapshot from .agent/manifest.json and the evidence system.',
    errorTitle: "Could not load AOS data",
    versionsHeading: "Versions",
    aosVersion: "AOS version",
    appVersion: "Application version",
    branch: "Branch",
    commit: "Commit",
    modulesHeading: "Modules",
    modulesTotal: "Total modules",
    viewAllModules: "View all modules",
    taskTypesHeading: "Supported task types",
    supportedAgentsHeading: "Supported agents",
    evidenceHeading: "Latest quality evidence",
    evidenceNone: "No evidence run yet. Run npm run quality:evidence.",
    evidenceGates: "Gates",
    evidencePassed: "Passed",
    evidenceFailed: "Failed",
    evidenceNotAvailable: "Not available",
    researchHeading: "Research pipeline",
    researchSources: "Sources",
    researchClaims: "Claims",
    researchCandidates: "Candidates",
    researchReviews: "Reviews",
    researchPublished: "Published",
    securityHeading: "Security policy",
    securityBody: "Security rules take precedence over every other instruction. See the full policy module.",
    gitHeading: "Git policy",
    releasesHeading: "Releases",
    handoffHeading: "Active handoff",
    handoffNone: "No handoff is currently active.",
    validationHeading: "AOS validation",
    validationOk: "No errors found",
    validationErrors: "Errors",
    subNavModules: "Modules",
    subNavResearch: "Research",
    subNavEvidence: "Evidence",
    subNavHandoffs: "Handoffs",
    subNavSecurity: "Security",
    subNavReleases: "Releases",
    backToDashboard: "Back to dashboard",
    category: "Category",
    status: "Status",
    requiredFor: "Required for",
    filterByCategory: "Filter by category",
    filterByTaskType: "Filter by task type",
    all: "All",
    showingOf: "Showing {shown} of {total}",
    loadMore: "Load more",
    generatedAt: "Generated",
    noResults: "No matching results.",
  },
} as const;

export type AosUiLanguage = keyof typeof aosUi;
export type AosUiKey = keyof (typeof aosUi)["en"];
