export const agentUi = {
  he: {
    library: "הסוכנים שלי",
    builder: "בונה האייג׳נטים",
    newAgent: "אייג׳נט חדש",
    empty: "עדיין לא שמרת אייג׳נטים",
    name: "שם האייג׳נט",
    description: "תיאור",
    goal: "מטרה",
    inputs: "קלטים",
    instructions: "הנחיות",
    tools: "כלים",
    memory: "זיכרון",
    validation: "בדיקות ואימות",
    retry: "מדיניות ניסיון חוזר",
    approval: "אישור אנושי",
    output: "פלט",
    completion: "תנאי סיום",
    review: "סקירה",
    previous: "הקודם",
    next: "הבא",
    save: "שמירת אייג׳נט",
    required: "שדה חובה",
    toolNotice:
      "בחירת הכלים מגדירה רק את תכנון האייג׳נט. בגרסה זו לא מחובר שירות חיצוני.",
    memoryNotice:
      "הבחירה מגדירה את ארכיטקטורת האייג׳נט בלבד. זיכרון חיצוני עדיין אינו פעיל.",
    notConnected: "לא מחובר",
    quality: "איכות תכנון",
    disclaimer:
      "ציון מבני בלבד; הוא אינו מוכיח מוכנות לייצור, אבטחה או הרשאות.",
    view: "צפייה",
    edit: "עריכה",
    duplicate: "שכפול",
    simulate: "סימולציה",
    export: "ייצוא",
    archive: "העברה לארכיון",
    delete: "מחיקה",
    favorite: "הוספה למועדפים",
    unfavorite: "הסרה מהמועדפים",
    copy: "עותק",
    search: "חיפוש אייג׳נטים",
    all: "הכול",
    favoritesOnly: "מועדפים בלבד",
    templates: "תבניות",
    useTemplate: "שימוש בתבנית",
    blueprint: "תוכנית אייג׳נט",
    simulationOnly: "סימולציה בלבד — לא הופעלו כלים חיצוניים.",
    scenario: "תרחיש",
    sampleInput: "קלט לדוגמה",
    run: "הרצת סימולציה",
    unknown: "האייג׳נט לא נמצא",
    confirmDelete: "למחוק את האייג׳נט?",
    cancel: "ביטול",
    ready: "מוכן",
    draft: "טיוטה",
    archived: "בארכיון",
    counts: "אייג׳נטים",
    help: "עזרה",
    openBuilder: "פתיחה בבונה האייג׳נטים",
  },
  en: {
    library: "Agent Library",
    builder: "Agent Builder",
    newAgent: "New Agent",
    empty: "You have not saved any Agents yet",
    name: "Agent name",
    description: "Description",
    goal: "Goal",
    inputs: "Inputs",
    instructions: "Instructions",
    tools: "Tools",
    memory: "Memory",
    validation: "Validation",
    retry: "Retry Policy",
    approval: "Human Approval",
    output: "Output",
    completion: "Completion Criteria",
    review: "Review",
    previous: "Previous",
    next: "Next",
    save: "Save Agent",
    required: "This field is required",
    toolNotice:
      "Tool selection defines the planned Agent design only. No external service is connected in this version.",
    memoryNotice:
      "This selection defines the Agent architecture only. External memory is not active yet.",
    notConnected: "Not connected",
    quality: "Design quality",
    disclaimer:
      "Structural score only; it does not prove production readiness, security, or permissions.",
    view: "View",
    edit: "Edit",
    duplicate: "Duplicate",
    simulate: "Simulate",
    export: "Export",
    archive: "Archive",
    delete: "Delete",
    favorite: "Add to favorites",
    unfavorite: "Remove from favorites",
    copy: "Copy",
    search: "Search Agents",
    all: "All",
    favoritesOnly: "Favorites only",
    templates: "Templates",
    useTemplate: "Use Template",
    blueprint: "Agent Blueprint",
    simulationOnly: "Simulation only — no external tools were executed.",
    scenario: "Scenario",
    sampleInput: "Sample input",
    run: "Run simulation",
    unknown: "Agent not found",
    confirmDelete: "Delete this Agent?",
    cancel: "Cancel",
    ready: "Ready",
    draft: "Draft",
    archived: "Archived",
    counts: "Agents",
    help: "Help",
    openBuilder: "Open in Agent Builder",
  },
} as const;
export const stepKeys = [
  "name",
  "goal",
  "inputs",
  "instructions",
  "tools",
  "memory",
  "validation",
  "retry",
  "approval",
  "output",
  "completion",
  "review",
] as const;
export const toolNames = {
  jiraReader: "Jira Reader",
  githubReader: "GitHub Reader",
  sqlQuery: "SQL Query Tool",
  testReport: "Test Report Reader",
  fileReader: "File Reader",
  webSearch: "Web Search",
  emailDraft: "Email Draft Tool",
  calendarReader: "Calendar Reader",
  notification: "Notification Tool",
  none: "No External Tools",
} as const;
