import { deterministicHash } from "./hash";

const UNSAFE = /(?:api[-_ ]?key|secret|password|token|authorization|credential|-----BEGIN|[a-z]:[\\/]|\/(?:users|home|private)\s*\/)/i;
const NAME = /^[a-z][a-z0-9_-]{1,63}$/;
const ALLOWED_PERMISSIONS = new Set(["read", "workspace-write", "network"]);

export interface CodexAgentDefinition {
  name: string;
  description: string;
  developerInstructions: string;
  permissions?: string[];
  provenance?: string;
}

export interface CodexExportResult {
  toml: string;
  checksum: string;
  omittedFields: string[];
  parsed: CodexAgentDefinition;
}

function assertSafe(value: string): void {
  if (UNSAFE.test(value) || value.includes("\0")) throw new Error("Agent export contains a secret, credential, or local path.");
}

export function parseCodexToml(toml: string): CodexAgentDefinition {
  if (toml.length > 100_000 || UNSAFE.test(toml)) throw new Error("Unsafe Codex TOML.");
  const parsed: Partial<CodexAgentDefinition> = {};
  for (const rawLine of toml.split(/\r?\n/)) {
    const line = rawLine.trim();
    if (!line || line.startsWith("#") || line === "[agent]") continue;
    const match = /^([a-z_]+)\s*=\s*(.+)$/.exec(line);
    if (!match) throw new Error("Unsupported TOML syntax.");
    const [, key, encoded] = match;
    if (key === "permissions") {
      const permissions = JSON.parse(encoded) as unknown;
      if (!Array.isArray(permissions) || !permissions.every((item) => typeof item === "string" && ALLOWED_PERMISSIONS.has(item))) {
        throw new Error("Unsupported permission.");
      }
      parsed.permissions = permissions;
    } else if (["name", "description", "developer_instructions", "provenance"].includes(key)) {
      const value = JSON.parse(encoded) as unknown;
      if (typeof value !== "string") throw new Error("Expected a TOML string.");
      if (key === "developer_instructions") parsed.developerInstructions = value;
      else parsed[key as "name" | "description" | "provenance"] = value;
    } else {
      throw new Error("Unsupported Codex Agent field.");
    }
  }
  if (!parsed.name || !NAME.test(parsed.name) || !parsed.description || !parsed.developerInstructions) {
    throw new Error("Codex Agent is missing required fields.");
  }
  return parsed as CodexAgentDefinition;
}

export function exportCodexAgent(input: CodexAgentDefinition): CodexExportResult {
  if (!NAME.test(input.name) || input.description.trim().length < 1 || input.description.length > 500
    || input.developerInstructions.trim().length < 1 || input.developerInstructions.length > 20_000) {
    throw new Error("Invalid Codex Agent definition.");
  }
  [input.description, input.developerInstructions, input.provenance ?? ""].forEach(assertSafe);
  const permissions = [...new Set(input.permissions ?? [])].filter((permission) => ALLOWED_PERMISSIONS.has(permission));
  const omittedFields = (input.permissions ?? []).filter((permission) => !ALLOWED_PERMISSIONS.has(permission))
    .map((permission) => `permissions:${permission}`);
  const lines = [
    "# Generated by Shabi's AI Academy Version 1.9",
    input.provenance ? `# Provenance: ${input.provenance.replace(/[\r\n]/g, " ")}` : undefined,
    "[agent]",
    `name = ${JSON.stringify(input.name)}`,
    `description = ${JSON.stringify(input.description)}`,
    `developer_instructions = ${JSON.stringify(input.developerInstructions)}`,
    permissions.length ? `permissions = ${JSON.stringify(permissions)}` : undefined,
  ].filter((line): line is string => line !== undefined);
  const toml = `${lines.join("\n")}\n`;
  const parsed = parseCodexToml(toml);
  if (parsed.name !== input.name || parsed.description !== input.description
    || parsed.developerInstructions !== input.developerInstructions) throw new Error("Codex TOML round-trip failed.");
  return { toml, checksum: deterministicHash(toml), omittedFields, parsed };
}
