export const userDocs = [
  ["curriculum", "Curriculum", "תוכנית לימודים", "Ten-module learning journey and lesson model."],
  ["prompt-packs", "Prompt Packs", "חבילות פרומפטים", "Built-in packs, imports, and ownership."],
  ["starter-agents", "Starter Agents", "סוכנים התחלתיים", "Catalog boundaries and planned tools."],
  ["prompt-playground", "Prompt Playground", "מגרש פרומפטים", "Mock, Dry Run, assembly, and history."],
  ["agent-playground", "Agent Playground", "מגרש סוכנים", "Runtime-backed agent scenarios."],
  ["projects", "Projects", "פרויקטים", "Local linking workspaces."],
  ["knowledge-base", "Knowledge Base", "מאגר ידע", "Supported local documents and search."],
  ["runtime", "Runtime Engine", "מנוע Runtime", "States, providers, approvals, retries, and cancellation."],
  ["testing", "Quality and testing", "איכות ובדיקות", "Automated and manual release evidence."],
  ["about", "About the Academy", "אודות האקדמיה", "Purpose, creator, privacy, technology, and limitations."],
  ["learning-journey", "Learning Journey", "מסע הלמידה", "Recommended paths without forced lesson locks."],
  ["project-templates", "Project Templates", "תבניות פרויקט", "Five local starter workspaces and safe linking."],
  ["knowledge-import", "Knowledge Import", "ייבוא ידע", "Supported formats, size limits, validation, and safe rendering."],
  ["qa-center", "QA Center", "מרכז QA", "Quality evidence, issue tracking, and the manual checklist."],
  ["release-center", "Release Center", "מרכז שחרור", "Version metadata, release gates, Preview review, and rollback."],
  ["live-provider", "Live Provider Boundary", "גבול ספק חי", "Why Live remains disabled and how the server boundary is reserved."],
  ["vercel-deployment", "Vercel Deployment", "פריסה ב-Vercel", "Public hosting, SPA routing, Preview verification, and rollback."],
  ["global-search", "Global Search", "חיפוש גלובלי", "Local indexing, ranking, filters, and keyboard navigation."],
  ["command-palette", "Command Palette", "לוח פקודות", "Typed commands, shortcuts, confirmations, and contextual actions."],
  ["assistant-sidebar", "Assistant Sidebar", "סרגל העוזר", "Route-aware local guidance across the Workspace."],
  ["local-assistant", "Local Assistant", "עוזר מקומי", "Deterministic intents, recommendations, and safe actions."],
  ["advanced-prompt-builder", "Advanced Prompt Builder", "בונה פרומפטים מתקדם", "Templates, local tests, quality guidance, history, and diffs."],
  ["advanced-agent-builder", "Advanced Agent Builder", "בונה סוכנים מתקדם", "Policies, local scenarios, validation, history, and diffs."],
  ["workflow-builder", "Workflow Builder", "בונה תהליכי עבודה", "Deterministic Mock and Dry Run workflows."],
  ["activity-analytics", "Activity and Analytics", "פעילות וניתוח נתונים", "Private local metadata, trends, and storage estimates."],
  ["workspace-export-import", "Workspace Export and Import", "ייצוא וייבוא סביבת עבודה", "Validated versioned backup, preview, conflicts, and rollback."],
  ["keyboard-shortcuts", "Keyboard Shortcuts", "קיצורי מקלדת", "Workspace shortcuts and safe keyboard behavior."],
] as const;
