import { test, expect, login, english, noOverflow } from "../fixtures/academy";
test("public About leads into the protected Academy", async ({ page }) => { await page.goto("/about"); await expect(page.getByRole("heading", { name: /לומדים AI באמצעות|Learn AI by building/ })).toBeVisible(); await expect(page.getByText(/Demo Login אינו|Demo Login is not/)).toBeVisible(); await page.getByRole("link", { name: /התחלת הלימוד|Start learning/ }).first().click(); await expect(page).toHaveURL(/\/login/); await page.goto("/"); await expect(page.getByRole("heading", { name: /לומדים AI דרך עשייה מודרכת|Learn AI through guided practice/ })).toBeVisible(); });
test("complete curriculum exposes 45 open lessons", async ({ page }) => { await login(page, "/lessons"); await expect(page.locator(".lesson-card")).toHaveCount(45); await page.locator(".lesson-card a").last().click(); await expect(page.getByText(/Mini-project|מיני־פרויקט/)).toBeVisible(); });
test("prompt packs support selected and full-pack imports", async ({ page }) => { await login(page); await english(page); await page.goto("/prompts/packs"); await expect(page.getByRole("heading", { name: "Prompt Packs" })).toBeVisible(); await expect(page.getByText(/^250 · Selected: 0$/)).toBeVisible(); await page.locator(".prompt-card input[type=checkbox]").first().check(); await page.getByRole("button", { name: /Import selected \(1\)/ }).click(); await page.locator(".prompt-filters select").first().selectOption("security-risk"); await page.getByRole("button", { name: "Import pack" }).click(); await page.goto("/prompts"); await expect(page.locator(".prompt-card")).toHaveCount(11); });
test("starter agents import and open local Mock simulation", async ({ page }) => { await login(page); await english(page); await page.goto("/agents/catalog"); await expect(page.locator(".prompt-card")).toHaveCount(32); await page.getByRole("button", { name: "Import" }).first().click(); await expect(page).toHaveURL(/\/agents\//); await page.goto("/playground/agents"); await page.getByRole("button", { name: "Import agent" }).click(); await page.getByRole("button", { name: "Run", exact: true }).click(); await expect(page.getByText("completed", { exact: true })).toBeVisible(); });

test("agent playground links the selected agent and run to a local project", async ({ page }) => {
  await page.addInitScript(() => localStorage.setItem("shabis-ai-academy.projects.v1", JSON.stringify({ schemaVersion: 1, projects: [{ id: "project-e2e", name: "Beta Review", description: "", category: "qa", status: "active", tags: [], promptIds: [], agentIds: [], runIds: [], documentIds: [], notes: "", activity: [], createdAt: "2026-07-13T00:00:00.000Z", updatedAt: "2026-07-13T00:00:00.000Z", version: 1, favorite: false, archived: false }] })));
  await login(page); await english(page); await page.goto("/playground/agents");
  await page.getByLabel("Select project").selectOption("project-e2e");
  await page.getByRole("button", { name: "Run", exact: true }).click();
  await page.getByRole("button", { name: "Save to project" }).click();
  await expect(page.getByRole("status")).toHaveText("Agent and run saved to the local project");
  const project = await page.evaluate(() => JSON.parse(localStorage.getItem("shabis-ai-academy.projects.v1")!).projects[0]);
  expect(project.agentIds).toHaveLength(1); expect(project.runIds).toHaveLength(1);
});
test("Prompt Playground runs Mock and Dry Run without external requests", async ({ page }) => { const external: string[] = []; page.on("request", (request) => { if (!request.url().startsWith("http://127.0.0.1")) external.push(request.url()); }); await login(page, "/playground/prompts"); await page.getByRole("button", { name: /הרצה|Run/ }).click(); await expect(page.getByText(/פלט Mock מדומה|Simulated Mock output/).last()).toBeVisible(); await page.getByLabel("Mode").selectOption("dryRun"); await page.getByRole("button", { name: /הרצה|Run/ }).click(); await expect(page.getByText(/תצוגה מקדימה בלבד|Preview only/).last()).toBeVisible(); expect(external).toEqual([]); });
test("projects and Knowledge Base persist and remain linked", async ({ page }) => { await login(page); await english(page); await page.goto("/projects/new"); await page.getByLabel("Template").selectOption("qa-release"); await page.getByRole("button", { name: "Save" }).click(); const projectUrl = page.url(); await page.getByRole("link", { name: "Add knowledge document" }).click(); await page.getByLabel("Title").fill("Release evidence"); await page.getByLabel("Content").fill("Verified local test evidence"); await page.getByRole("button", { name: "Save" }).click(); await page.reload(); await expect(page.getByText("Verified local test evidence")).toBeVisible(); await page.goto(projectUrl); await expect(page.getByText(/Documents/)).toBeVisible(); });
test("platform centers are protected, bilingual, and direct-route safe", async ({ page }) => { for (const route of ["/journey", "/roadmap", "/changelog", "/docs", "/release", "/developer"]) { await page.goto(route); await expect(page).toHaveURL(/\/login\?from=/); } await login(page); await english(page); for (const route of ["/journey", "/roadmap", "/changelog", "/docs", "/release", "/developer"]) { await page.goto(route); await page.reload(); await expect(page.locator("h1")).toBeVisible(); } });
test("new beta workspaces have no horizontal overflow on mobile", async ({ page }) => { await page.setViewportSize({ width: 320, height: 568 }); await page.goto("/about"); await noOverflow(page); await login(page, "/playground/prompts"); await noOverflow(page); await page.goto("/projects"); await noOverflow(page); await page.goto("/knowledge"); await noOverflow(page); });
