import type { RadarItem } from "./types";

export const radarSourceHosts = Object.freeze([
  "openai.com",
  "www.anthropic.com",
  "deepmind.google",
  "huggingface.co",
  "www.nist.gov",
] as const);

export const radarItems: readonly RadarItem[] = Object.freeze([
  {
    id: "openai-gpt-5-6",
    publisher: "OpenAI",
    sourceUrl: "https://openai.com/index/gpt-5-6/",
    publishedAt: "2026-07-09",
    verifiedAt: "2026-07-13",
    category: "models",
    horizon: "now",
    featured: true,
    title: { he: "משפחת המודלים GPT-5.6", en: "The GPT-5.6 model family" },
    summary: {
      he: "OpenAI הכריזה על משפחת Sol, Terra ו-Luna עם דגש על יעילות, עבודת ידע, שימוש בכלים ותזמור מרובה סוכנים.",
      en: "OpenAI announced the Sol, Terra, and Luna family with an emphasis on efficiency, knowledge work, tool use, and multi-agent orchestration.",
    },
    implication: {
      he: "כדאי להעריך מודלים לפי איכות כוללת, זמן ועלות של המשימה — ולא לפי ציון יחיד.",
      en: "Evaluate models by end-to-end task quality, time, and cost rather than a single benchmark score.",
    },
  },
  {
    id: "anthropic-sonnet-5",
    publisher: "Anthropic",
    sourceUrl: "https://www.anthropic.com/news/claude-sonnet-5",
    publishedAt: "2026-06-30",
    verifiedAt: "2026-07-13",
    category: "models",
    horizon: "now",
    featured: true,
    title: { he: "Claude Sonnet 5 למשימות סוכנית", en: "Claude Sonnet 5 for agentic work" },
    summary: {
      he: "Anthropic מציגה שיפור בתכנון, שימוש בכלים, קוד ועבודת ידע, לצד אפשרויות מאמץ שמאזנות עלות וביצועים.",
      en: "Anthropic reports improvements in planning, tool use, coding, and knowledge work, with effort controls that trade cost for performance.",
    },
    implication: {
      he: "בדיקות סוכנים צריכות לכלול מסלולים ארוכים, כלים, כשל והתאוששות — לא רק תשובה סופית.",
      en: "Agent tests should cover long trajectories, tools, failure, and recovery—not only the final answer.",
    },
  },
  {
    id: "deepmind-agent-control",
    publisher: "Google DeepMind",
    sourceUrl: "https://deepmind.google/blog/securing-the-future-of-ai-agents/",
    publishedAt: "2026-06-18",
    verifiedAt: "2026-07-13",
    category: "safety",
    horizon: "next",
    featured: true,
    title: { he: "בקרות מערכתיות לסוכני AI", en: "System-level controls for AI agents" },
    summary: {
      he: "מפת הדרכים של DeepMind משלבת מידול איומים, ניטור, הרשאות מדורגות ומניעה בזמן אמת עבור סוכנים בעלי יכולת גבוהה.",
      en: "DeepMind's roadmap combines threat modeling, monitoring, graduated permissions, and real-time prevention for increasingly capable agents.",
    },
    implication: {
      he: "יש לתכנן הרשאות, פיקוח ויכולת עצירה כחלק מארכיטקטורת הסוכן, לא כתוספת מאוחרת.",
      en: "Permissions, supervision, and shutdown paths belong in the agent architecture, not as late additions.",
    },
  },
  {
    id: "huggingface-agent-evaluation",
    publisher: "Hugging Face",
    sourceUrl: "https://huggingface.co/blog/is-it-agentic-enough",
    publishedAt: "2026-06-18",
    verifiedAt: "2026-07-13",
    category: "evaluation",
    horizon: "now",
    featured: false,
    title: { he: "הערכת התנהגות סוכנית", en: "Evaluating agentic behavior" },
    summary: {
      he: "המאמר בוחן כיצד להבחין בין מודל שמייצר תשובות לבין מערכת שמתכננת, פועלת ומסתגלת בסביבה.",
      en: "The article examines how to distinguish answer generation from systems that plan, act, and adapt within an environment.",
    },
    implication: {
      he: "הגדירו מראש מה נחשב פעולה, הסתגלות והצלחה לפני בחירת מדד או benchmark.",
      en: "Define action, adaptation, and success before selecting a metric or benchmark.",
    },
  },
  {
    id: "deepmind-multi-agent-safety",
    publisher: "Google DeepMind",
    sourceUrl: "https://deepmind.google/blog/investing-in-multi-agent-ai-safety-research/",
    publishedAt: "2026-06-11",
    verifiedAt: "2026-07-13",
    category: "safety",
    horizon: "watch",
    featured: false,
    title: { he: "בטיחות במערכות מרובות סוכנים", en: "Safety in multi-agent systems" },
    summary: {
      he: "DeepMind מתארת השקעה במחקר על תיאום, התנהגות מתהווה וסיכונים שנוצרים מאינטראקציה בין כמה סוכנים.",
      en: "DeepMind describes research investment in coordination, emergent behavior, and risks created by interactions among multiple agents.",
    },
    implication: {
      he: "בדיקת כל סוכן בנפרד אינה מספיקה; נדרש גם אימות של התנהגות המערכת המשותפת.",
      en: "Testing each agent independently is insufficient; the combined system behavior also needs validation.",
    },
  },
  {
    id: "huggingface-openenv",
    publisher: "Hugging Face",
    sourceUrl: "https://huggingface.co/blog/openenv-agentic-rl",
    publishedAt: "2026-06-08",
    verifiedAt: "2026-07-13",
    category: "open-source",
    horizon: "next",
    featured: false,
    title: { he: "סביבות פתוחות ללמידת סוכנים", en: "Open environments for agent learning" },
    summary: {
      he: "OpenEnv מציעה ממשק פתוח ומודולרי לסביבות שבהן סוכנים יכולים להתאמן ולהיבדק באמצעות אינטראקציה.",
      en: "OpenEnv proposes an open, modular interface for environments where agents can train and be evaluated through interaction.",
    },
    implication: {
      he: "סביבות ניתנות לשחזור מאפשרות להשוות מדיניות סוכן בלי לקשור את הבדיקה לספק יחיד.",
      en: "Reproducible environments make it easier to compare agent policies without binding evaluation to one provider.",
    },
  },
  {
    id: "deepmind-ai-co-scientist",
    publisher: "Google DeepMind",
    sourceUrl: "https://deepmind.google/blog/co-scientist-a-multi-agent-ai-partner-to-accelerate-research/",
    publishedAt: "2026-05-19",
    verifiedAt: "2026-07-13",
    category: "agents",
    horizon: "watch",
    featured: false,
    title: { he: "שותף מחקר מרובה סוכנים", en: "A multi-agent research partner" },
    summary: {
      he: "מערכת AI co-scientist מדגימה חלוקת תפקידים סוכנית ליצירת השערות, ביקורת, דירוג ושיפור הצעות מחקר.",
      en: "The AI co-scientist system demonstrates agent roles for generating hypotheses, critique, ranking, and refining research proposals.",
    },
    implication: {
      he: "תהליכים מרובי סוכנים מועילים כאשר תפקידים, ראיות ונקודות החלטה ניתנים לביקורת אנושית.",
      en: "Multi-agent workflows are most useful when roles, evidence, and decision points remain available for human review.",
    },
  },
  {
    id: "nist-ai-rmf-update",
    publisher: "NIST",
    sourceUrl: "https://www.nist.gov/itl/ai-risk-management-framework",
    publishedAt: "2026-04-07",
    verifiedAt: "2026-07-13",
    category: "governance",
    horizon: "next",
    featured: false,
    title: { he: "התפתחות מסגרת ניהול סיכוני AI", en: "The AI Risk Management Framework evolves" },
    summary: {
      he: "NIST ממשיך לעדכן את משאבי AI RMF, כולל עבודת פרופיל לתשתיות קריטיות ותהליך תיקון למסגרת.",
      en: "NIST continues to update AI RMF resources, including critical-infrastructure profile work and a framework revision process.",
    },
    implication: {
      he: "מיפוי, מדידה, ניהול וממשל צריכים להופיע כפעולות מתמשכות לאורך מחזור החיים.",
      en: "Map, measure, manage, and govern should be continuous lifecycle activities rather than a launch checklist.",
    },
  },
]);
