import type { KnowledgeDocument, KnowledgeInput, KnowledgeState } from "./types";
export const KNOWLEDGE_STORAGE_KEY = "shabis-ai-academy.knowledge.v1"; export const MAX_KNOWLEDGE_BYTES = 1_000_000;
export const emptyKnowledgeState = (): KnowledgeState => ({ schemaVersion: 1, documents: [] });
const valid = (value: unknown): value is KnowledgeDocument => Boolean(value && typeof value === "object" && typeof (value as KnowledgeDocument).id === "string" && typeof (value as KnowledgeDocument).content === "string" && (value as KnowledgeDocument).size <= MAX_KNOWLEDGE_BYTES);
export function loadKnowledgeState(): KnowledgeState { try { const parsed = JSON.parse(localStorage.getItem(KNOWLEDGE_STORAGE_KEY) ?? "null") as KnowledgeState | null; return parsed?.schemaVersion === 1 && Array.isArray(parsed.documents) ? { schemaVersion: 1, documents: parsed.documents.filter(valid) } : emptyKnowledgeState(); } catch { return emptyKnowledgeState(); } }
export function saveKnowledgeState(state: KnowledgeState) { try { localStorage.setItem(KNOWLEDGE_STORAGE_KEY, JSON.stringify(state)); return true; } catch { return false; } }
const hash = (value: string) => { let result = 2166136261; for (const char of value) result = Math.imul(result ^ char.charCodeAt(0), 16777619); return (result >>> 0).toString(16); };
export function sanitizeFilename(name: string) { return name.replace(/[^a-zA-Z0-9._-]/g, "_").slice(0, 120); }
export function validateKnowledgeInput(input: KnowledgeInput): string[] { const bytes = new TextEncoder().encode(input.content).length; const errors: string[] = []; if (!input.title.trim()) errors.push("titleRequired"); if (!input.content.trim()) errors.push("contentRequired"); if (bytes > MAX_KNOWLEDGE_BYTES) errors.push("tooLarge"); if (!["text", "markdown", "json", "csv", "note"].includes(input.contentType)) errors.push("unsupportedType"); if (input.contentType === "json") try { JSON.parse(input.content); } catch { errors.push("malformedJson"); } return errors; }
export function createKnowledgeDocument(input: KnowledgeInput): KnowledgeDocument { const errors = validateKnowledgeInput(input); if (errors.length) throw new Error(errors.join(",")); const now = new Date().toISOString(); const size = new TextEncoder().encode(input.content).length; return { ...input, filename: input.filename ? sanitizeFilename(input.filename) : undefined, id: crypto.randomUUID(), size, createdAt: now, updatedAt: now, version: 1, hash: hash(input.content), status: "ready" }; }
export function searchKnowledge(documents: readonly KnowledgeDocument[], query: string) { const normalized = query.trim().toLocaleLowerCase(); if (!normalized) return documents; return documents.filter((document) => `${document.title} ${document.description} ${document.content} ${document.tags.join(" ")} ${document.source}`.toLocaleLowerCase().includes(normalized)); }
