import type { Outcome } from "../outcomes/types";
import type { Project, ProjectInput, ProjectLinkField, ProjectState } from "./types";
export const PROJECT_STORAGE_KEY = "shabis-ai-academy.projects.v1";
export const emptyProjectState = (): ProjectState => ({ schemaVersion: 2, projects: [] });
const valid = (value: unknown): value is Project => Boolean(value && typeof value === "object" && typeof (value as Project).id === "string" && typeof (value as Project).name === "string" && Array.isArray((value as Project).promptIds));
const strings = (value: unknown) => Array.isArray(value) ? value.filter((item): item is string => typeof item === "string") : [];
export function migrateProject(project: Project | (Partial<Project> & Pick<Project,"id"|"name">)): Project {
  return { ...project, description: project.description ?? "", category: project.category ?? "general", status: project.status ?? "planning", tags: strings(project.tags), notes: project.notes ?? "", promptIds: strings(project.promptIds), agentIds: strings(project.agentIds), runIds: strings(project.runIds), documentIds: strings(project.documentIds), objective: project.objective ?? project.description ?? "", targetOutcome: project.targetOutcome ?? "", outcomeIds: strings(project.outcomeIds), teamIds: strings(project.teamIds), missionIds: strings(project.missionIds), workflowIds: strings(project.workflowIds), evidenceIds: strings(project.evidenceIds), deliverableIds: strings(project.deliverableIds), decisions: Array.isArray(project.decisions) ? project.decisions : [], risks: Array.isArray(project.risks) ? project.risks : [], blockers: strings(project.blockers), nextActions: strings(project.nextActions), activity: Array.isArray(project.activity) ? project.activity : [], createdAt: project.createdAt ?? new Date(0).toISOString(), updatedAt: project.updatedAt ?? project.createdAt ?? new Date(0).toISOString(), version: Math.max(1, project.version ?? 1), favorite: project.favorite === true, archived: project.archived === true };
}
export function loadProjectState(): ProjectState { try { const parsed = JSON.parse(localStorage.getItem(PROJECT_STORAGE_KEY) ?? "null") as { schemaVersion?: number; projects?: unknown[] } | null; return parsed && (parsed.schemaVersion === 1 || parsed.schemaVersion === 2) && Array.isArray(parsed.projects) ? { schemaVersion: 2, projects: parsed.projects.filter(valid).map((project) => migrateProject(project)) } : emptyProjectState(); } catch { return emptyProjectState(); } }
export function saveProjectState(state: ProjectState) { try { localStorage.setItem(PROJECT_STORAGE_KEY, JSON.stringify(state)); return true; } catch { return false; } }
export function createProject(input: ProjectInput): Project { const now = new Date().toISOString(); return { ...input, id: crypto.randomUUID(), promptIds: [], agentIds: [], runIds: [], documentIds: [], objective: input.description, targetOutcome: "", outcomeIds: [], teamIds: [], missionIds: [], workflowIds: [], evidenceIds: [], deliverableIds: [], decisions: [], risks: [], blockers: [], nextActions: [], activity: [{ id: crypto.randomUUID(), timestamp: now, summary: "Project created" }], createdAt: now, updatedAt: now, version: 1, favorite: false, archived: false }; }
export function updateProject(project: Project, patch: Partial<Project>): Project { return { ...project, ...patch, id: project.id, version: project.version + 1, updatedAt: new Date().toISOString() }; }
export function linkProjectItem(project: Project, field: ProjectLinkField, id: string): Project { if (project[field].includes(id)) return project; return updateProject(project, { [field]: [...project[field], id], activity: [{ id: crypto.randomUUID(), timestamp: new Date().toISOString(), summary: `Linked ${field.slice(0, -3)}` }, ...project.activity].slice(0, 50) }); }
export function unlinkProjectItem(project: Project, field: ProjectLinkField, id: string): Project { return updateProject(project, { [field]: project[field].filter((value) => value !== id), activity: [{ id: crypto.randomUUID(), timestamp: new Date().toISOString(), summary: `Unlinked ${field.slice(0, -3)}` }, ...project.activity].slice(0, 50) }); }
export function calculateProjectProgress(project: Project, outcomes: Array<Pick<Outcome, "id" | "status" | "verificationState" | "realityMode">>): number {
  const linked = outcomes.filter((outcome) => project.outcomeIds.includes(outcome.id) && outcome.status !== "archived");
  if (!linked.length) return 0;
  const score = linked.reduce((total, outcome) => total + (outcome.verificationState === "verified" ? 1 : outcome.status === "blocked" ? 0 : outcome.status === "completed" ? (outcome.realityMode === "simulated" ? 0.4 : 0.7) : outcome.status === "needs-evidence" ? 0.25 : 0.1), 0);
  const blockerPenalty = Math.min(0.5, project.blockers.length * 0.1);
  return Math.max(0, Math.min(100, Math.round((score / linked.length - blockerPenalty) * 100)));
}
