import type { Project, ProjectInput, ProjectState } from "./types";
export const PROJECT_STORAGE_KEY = "shabis-ai-academy.projects.v1";
export const emptyProjectState = (): ProjectState => ({ schemaVersion: 1, projects: [] });
const valid = (value: unknown): value is Project => Boolean(value && typeof value === "object" && typeof (value as Project).id === "string" && typeof (value as Project).name === "string" && Array.isArray((value as Project).promptIds));
export function loadProjectState(): ProjectState { try { const parsed = JSON.parse(localStorage.getItem(PROJECT_STORAGE_KEY) ?? "null") as ProjectState | null; return parsed?.schemaVersion === 1 && Array.isArray(parsed.projects) ? { schemaVersion: 1, projects: parsed.projects.filter(valid) } : emptyProjectState(); } catch { return emptyProjectState(); } }
export function saveProjectState(state: ProjectState) { try { localStorage.setItem(PROJECT_STORAGE_KEY, JSON.stringify(state)); return true; } catch { return false; } }
export function createProject(input: ProjectInput): Project { const now = new Date().toISOString(); return { ...input, id: crypto.randomUUID(), promptIds: [], agentIds: [], runIds: [], documentIds: [], activity: [{ id: crypto.randomUUID(), timestamp: now, summary: "Project created" }], createdAt: now, updatedAt: now, version: 1, favorite: false, archived: false }; }
export function updateProject(project: Project, patch: Partial<Project>): Project { return { ...project, ...patch, id: project.id, version: project.version + 1, updatedAt: new Date().toISOString() }; }
export function linkProjectItem(project: Project, field: "promptIds" | "agentIds" | "runIds" | "documentIds", id: string): Project { if (project[field].includes(id)) return project; return updateProject(project, { [field]: [...project[field], id], activity: [{ id: crypto.randomUUID(), timestamp: new Date().toISOString(), summary: `Linked ${field.slice(0, -3)}` }, ...project.activity].slice(0, 50) }); }
export function unlinkProjectItem(project: Project, field: "promptIds" | "agentIds" | "runIds" | "documentIds", id: string): Project { return updateProject(project, { [field]: project[field].filter((value) => value !== id), activity: [{ id: crypto.randomUUID(), timestamp: new Date().toISOString(), summary: `Unlinked ${field.slice(0, -3)}` }, ...project.activity].slice(0, 50) }); }
