export const promptUi = {
  he: {
    library: "ספריית פרומפטים",
    workshop: "סדנת הפרומפטים",
    newPrompt: "פרומפט חדש",
    title: "שם הפרומפט",
    description: "תיאור",
    language: "שפה",
    category: "קטגוריה",
    tags: "תגיות",
    role: "תפקיד",
    task: "משימה",
    context: "הקשר",
    constraints: "מגבלות",
    outputFormat: "פורמט פלט",
    examples: "דוגמאות",
    notes: "הערות",
    save: "שמירה",
    required: "שדה חובה",
    preview: "תצוגה מקדימה",
    copy: "העתקה",
    copied: "הפרומפט הועתק",
    copyError: "לא ניתן להעתיק",
    quality: "איכות מבנית",
    disclaimer: "הציון בודק מבנה בלבד ואינו מבטיח נכונות או בטיחות.",
    needsWork: "דורש שיפור",
    foundation: "בסיס טוב",
    strong: "פרומפט חזק",
    excellent: "מבנה מצוין",
    empty: "עדיין לא שמרת פרומפטים",
    createFirst: "יצירת הפרומפט הראשון",
    search: "חיפוש בפרומפטים",
    all: "הכול",
    favoritesOnly: "מועדפים בלבד",
    clear: "ניקוי מסננים",
    results: "תוצאות",
    view: "צפייה",
    edit: "עריכה",
    duplicate: "שכפול",
    export: "ייצוא",
    delete: "מחיקה",
    favorite: "הוספה למועדפים",
    unfavorite: "הסרה מהמועדפים",
    version: "גרסה",
    notFound: "הפרומפט לא נמצא",
    back: "חזרה לספרייה",
    confirmDelete: "מחיקת הפרומפט?",
    confirmDescription:
      "הפעולה תמחק את הפרומפט מהדפדפן המקומי ולא ניתן לבטל אותה.",
    cancel: "ביטול",
    loadExamples: "טעינת דוגמאות",
    copySuffix: "עותק",
    saved: "הפרומפט נשמר",
    deleted: "הפרומפט נמחק",
    updated: "הפרומפט עודכן",
    total: "פרומפטים",
    favorites: "מועדפים",
    createPrompt: "יצירת פרומפט",
    openWorkshop: "פתח בסדנת הפרומפטים",
    sort: "מיון",
    updatedSort: "עודכן לאחרונה",
    createdSort: "תאריך יצירה",
    titleSort: "שם",
    qualitySort: "ציון איכות",
    noResults: "לא נמצאו פרומפטים",
    txt: "קובץ טקסט",
    md: "Markdown",
  },
  en: {
    library: "Prompt Library",
    workshop: "Prompt Workshop",
    newPrompt: "New Prompt",
    title: "Prompt Title",
    description: "Description",
    language: "Language",
    category: "Category",
    tags: "Tags",
    role: "Role",
    task: "Task",
    context: "Context",
    constraints: "Constraints",
    outputFormat: "Output Format",
    examples: "Examples",
    notes: "Notes",
    save: "Save Prompt",
    required: "This field is required",
    preview: "Live Preview",
    copy: "Copy",
    copied: "Prompt copied",
    copyError: "Unable to copy",
    quality: "Structural quality",
    disclaimer:
      "This score evaluates structure only and does not guarantee correctness or safety.",
    needsWork: "Needs work",
    foundation: "Good foundation",
    strong: "Strong prompt",
    excellent: "Excellent structure",
    empty: "You have not saved any prompts yet",
    createFirst: "Create your first prompt",
    search: "Search prompts",
    all: "All",
    favoritesOnly: "Favorites only",
    clear: "Clear filters",
    results: "results",
    view: "View",
    edit: "Edit",
    duplicate: "Duplicate",
    export: "Export",
    delete: "Delete",
    favorite: "Add to favorites",
    unfavorite: "Remove from favorites",
    version: "Version",
    notFound: "Prompt not found",
    back: "Back to Library",
    confirmDelete: "Delete this prompt?",
    confirmDescription:
      "This removes the prompt from this browser and cannot be undone.",
    cancel: "Cancel",
    loadExamples: "Load examples",
    copySuffix: "Copy",
    saved: "Prompt saved",
    deleted: "Prompt deleted",
    updated: "Prompt updated",
    total: "prompts",
    favorites: "favorites",
    createPrompt: "Create Prompt",
    openWorkshop: "Open in Prompt Workshop",
    sort: "Sort",
    updatedSort: "Last updated",
    createdSort: "Created date",
    titleSort: "Title",
    qualitySort: "Quality score",
    noResults: "No prompts match these filters",
    txt: "Text file",
    md: "Markdown",
  },
} as const;
export const categoryLabels = {
  he: {
    qa: "QA",
    sql: "SQL",
    jira: "Jira",
    release: "ניהול גרסאות",
    product: "מוצר",
    customer: "תקשורת עם לקוחות",
    development: "פיתוח",
    learning: "למידה",
    general: "כללי",
  },
  en: {
    qa: "QA",
    sql: "SQL",
    jira: "Jira",
    release: "Release Management",
    product: "Product",
    customer: "Customer Communication",
    development: "Development",
    learning: "Learning",
    general: "General",
  },
} as const;
